import { ToolCombination } from '@/types';

const combinations: ToolCombination[] = [
  {
    id: 'combo-1',
    slug: 'genspark-x-notion',
    title: 'Genspark × Notion｜AIリサーチ結果を自動で整理する方法',
    description: 'Gensparkで深掘りリサーチした情報をNotionに整理。情報収集から知識管理まで一気通貫のワークフローを構築。',
    longDescription: 'Gensparkの強力なAI検索機能とNotionの柔軟なナレッジ管理を組み合わせることで、情報収集から整理・活用までをシームレスに行えるワークフローが完成します。Gensparkは複数のソースから情報をSparkpageに統合し、一画面で包括的な調査結果を提示してくれます。従来のGoogle検索では複数のタブを開いて情報を比較する必要がありましたが、Gensparkなら1回の検索で必要な情報が揃います。収集した情報をNotionのデータベースに保存すれば、タグやプロパティで分類でき、後から横断検索も可能です。週次のリサーチ業務、競合分析、市場調査など、定期的な情報収集タスクに特に威力を発揮します。このワークフローを導入することで、リサーチにかかる時間を従来の3分の1程度に短縮でき、かつ情報の抜け漏れも減らせます。',
    toolA: 'Genspark',
    toolASlug: 'genspark',
    toolB: 'Notion',
    toolBSlug: 'notion',
    category: 'リサーチ × 整理',
    useCase: '市場調査・競合分析・学習ノート作成',
    steps: [
      { step: 1, action: 'Gensparkでリサーチ', tool: 'Genspark', description: 'テーマを入力してSuper Agentが複数ソースから情報を収集・要約' },
      { step: 2, action: 'リサーチ結果をコピー', tool: 'Genspark', description: '生成されたレポートのテキスト・リンクをコピー' },
      { step: 3, action: 'Notionに構造化して保存', tool: 'Notion', description: 'データベースに日付・テーマ・要約・ソースURLを記録' },
      { step: 4, action: 'Notionで分析・共有', tool: 'Notion', description: 'フィルタ・ビューで情報を整理しチームに共有' },
    ],
    benefits: ['リサーチ時間を1/3に短縮', '情報の散逸を防止', 'チームでの知識共有が簡単', 'ソースURL付きで信頼性を担保'],
    tags: ['Genspark', 'Notion', 'リサーチ', '情報整理', 'ナレッジ管理'],
  },
  {
    id: 'combo-2',
    slug: 'genspark-x-elevenlabs',
    title: 'Genspark × ElevenLabs｜AIリサーチからナレーション動画を作る',
    description: 'Gensparkで調べた内容をElevenLabsで音声化。解説動画やポッドキャストのコンテンツ制作を自動化。',
    longDescription: 'GensparkでリサーチしたコンテンツをElevenLabsで音声化するこの組み合わせは、ポッドキャストやオーディオコンテンツの制作を劇的に効率化します。Gensparkで特定のテーマについて深くリサーチし、その結果を基にナレーション原稿を作成、ElevenLabsで自然な音声に変換するという流れです。ElevenLabsの音声は感情表現が豊かで、リスナーがAI生成と気づかないレベルの品質です。ニュース解説チャンネル、教育コンテンツ、業界レポートの音声版など、テキストベースの情報を音声メディアに展開したい場面で活躍します。Gensparkの無料プランとElevenLabsの月5ドルプランだけで始められるため、初期投資もほぼゼロ。リサーチから音声配信まで1時間以内で完了できるこの組み合わせは、個人クリエイターにとって非常にコスパの高い選択肢です。',
    toolA: 'Genspark',
    toolASlug: 'genspark',
    toolB: 'ElevenLabs',
    toolBSlug: 'elevenlabs',
    category: 'リサーチ × 音声',
    useCase: '解説動画・ポッドキャスト・教育コンテンツ',
    steps: [
      { step: 1, action: 'テーマをリサーチ', tool: 'Genspark', description: 'トピックについて包括的な情報を収集' },
      { step: 2, action: '台本に変換', tool: 'Genspark', description: 'リサーチ結果を読み上げ用の台本形式に変換' },
      { step: 3, action: 'ナレーション生成', tool: 'ElevenLabs', description: '台本をElevenLabsに貼り付けて自然な音声を生成' },
      { step: 4, action: '音声を活用', tool: '動画編集ツール', description: '生成した音声を動画やポッドキャストに組み込む' },
    ],
    benefits: ['リサーチから音声まで30分で完成', '声出し不要でコンテンツ制作', '多言語対応で海外展開可能', '一貫した声質でブランディング'],
    tags: ['Genspark', 'ElevenLabs', 'ナレーション', '解説動画', 'ポッドキャスト'],
  },
  {
    id: 'combo-3',
    slug: 'genspark-x-heygen',
    title: 'Genspark × HeyGen｜リサーチからAIアバター動画を自動生成',
    description: 'Gensparkで情報収集、HeyGenでアバター動画に変換。企業紹介・教育コンテンツをAIだけで制作。',
    longDescription: 'GensparkのAI検索で集めた情報をHeyGenのAIアバターが解説する動画を作るこの組み合わせは、教育コンテンツや解説動画の制作に最適です。Gensparkで最新のデータや事実を収集し、それを基に台本を構成、HeyGenでリアルなAIアバターが話す動画として出力します。従来、こうした解説動画を作るには撮影環境の準備、出演者の確保、編集作業と多大な時間とコストが必要でした。この組み合わせなら、テキスト入力だけで完結します。HeyGenのアバターは40以上の言語に対応しているため、同じ台本から多言語版の動画を簡単に作成でき、グローバル展開にも対応可能です。企業の社内研修動画、製品紹介動画、オンライン講座など、プロフェッショナルな動画を低コストで量産したい場面で大きな価値を発揮します。',
    toolA: 'Genspark',
    toolASlug: 'genspark',
    toolB: 'HeyGen',
    toolBSlug: 'heygen',
    category: 'リサーチ × 動画',
    useCase: '企業紹介動画・教育コンテンツ・プレゼン動画',
    steps: [
      { step: 1, action: '内容をリサーチ', tool: 'Genspark', description: '動画のテーマについて包括的に調査' },
      { step: 2, action: '台本を作成', tool: 'Genspark', description: 'リサーチ結果から2〜3分の台本を生成' },
      { step: 3, action: 'アバター動画を生成', tool: 'HeyGen', description: '台本を入力しアバター・背景を選んで動画生成' },
      { step: 4, action: '動画を書き出し', tool: 'HeyGen', description: 'MP4でダウンロードして各プラットフォームに投稿' },
    ],
    benefits: ['顔出し不要で動画制作', '撮影・編集スキル不要', '多言語アバターで海外展開', '1本あたり20分で完成'],
    tags: ['Genspark', 'HeyGen', 'アバター動画', 'AI動画', '企業動画'],
  },
  {
    id: 'combo-4',
    slug: 'perplexity-x-notion',
    title: 'Perplexity × Notion｜出典付きリサーチを知識データベース化',
    description: 'Perplexityの出典付き検索結果をNotionに蓄積。信頼性の高い情報をチームで共有できる知識基盤を構築。',
    longDescription: 'PerplexityのAI検索とNotionのナレッジ管理を組み合わせることで、信頼性の高いリサーチ結果を体系的に蓄積・活用できるワークフローが構築できます。Perplexityは回答に明確な引用リンクを付けてくれるため、情報の出典を確認しやすく、学術的なリサーチやファクトチェックが必要な場面で特に有用です。有効リンク率97パーセントという高い精度で、信頼できるソースからの情報を提供してくれます。調査結果をNotionに保存する際は、出典URLも一緒に記録することで、後から原典に遡って詳細を確認できます。研究者、ライター、アナリストなど、正確な情報に基づいてコンテンツを作成する必要がある人にとって、この組み合わせは日々の業務を支える基盤となります。月額コストはPerplexity Pro 20ドルとNotion無料プランで始められます。',
    toolA: 'Perplexity',
    toolASlug: 'perplexity',
    toolB: 'Notion',
    toolBSlug: 'notion',
    category: 'リサーチ × 整理',
    useCase: '学術リサーチ・ビジネスインテリジェンス・チーム知識共有',
    steps: [
      { step: 1, action: '出典付きで検索', tool: 'Perplexity', description: 'Pro Searchで質問し、出典リンク付きの回答を取得' },
      { step: 2, action: '回答を整理', tool: 'Perplexity', description: 'フォローアップ質問で深掘りし、必要な情報を網羅' },
      { step: 3, action: 'Notionに構造化保存', tool: 'Notion', description: 'テーマ・要約・出典URL・日付をデータベースに記録' },
      { step: 4, action: 'ナレッジベースとして活用', tool: 'Notion', description: 'タグ・フィルタで横断検索し、レポートや記事に活用' },
    ],
    benefits: ['全情報に出典が付いて信頼性が高い', 'リサーチの再現性を確保', 'チーム全員が同じ情報にアクセス', '過去のリサーチを即座に検索可能'],
    tags: ['Perplexity', 'Notion', '出典付き', 'ナレッジベース', 'チーム共有'],
  },
  {
    id: 'combo-5',
    slug: 'perplexity-x-elevenlabs',
    title: 'Perplexity × ElevenLabs｜最新情報を音声ニュースに変換',
    description: 'Perplexityで最新ニュースを要約し、ElevenLabsで音声化。通勤中に聴けるパーソナルニュースを毎朝自動生成。',
    longDescription: 'Perplexityで正確にリサーチした情報をElevenLabsで音声コンテンツに変換するこの組み合わせは、信頼性の高いオーディオコンテンツの制作に最適です。Perplexityの強みは引用の正確さにあり、97パーセントの有効リンク率で信頼できるソースからの情報を提供します。この正確な情報を基にナレーション原稿を作成し、ElevenLabsの自然な音声で読み上げれば、リスナーに信頼される音声コンテンツが完成します。特にニュース解説、医療健康情報、金融市場分析など、正確性が求められるジャンルのポッドキャストやオーディオブックに向いています。ElevenLabsは29言語以上に対応しているため、海外向けコンテンツの制作も容易です。リサーチから音声出力まで約45分で完了し、月額約25ドルで運用可能です。',
    toolA: 'Perplexity',
    toolASlug: 'perplexity',
    toolB: 'ElevenLabs',
    toolBSlug: 'elevenlabs',
    category: 'リサーチ × 音声',
    useCase: '音声ニュース・ポッドキャスト・情報キャッチアップ',
    steps: [
      { step: 1, action: '最新ニュースを収集', tool: 'Perplexity', description: '業界の最新ニュースを検索し要約を取得' },
      { step: 2, action: '読み上げ台本に変換', tool: 'Perplexity', description: '要約を3〜5分の読み上げ用テキストに整形' },
      { step: 3, action: '音声を生成', tool: 'ElevenLabs', description: '台本から自然な音声ファイルを生成' },
      { step: 4, action: '音声を配信', tool: 'Spotify等', description: 'ポッドキャストとして配信、または個人で聴取' },
    ],
    benefits: ['毎朝5分で業界ニュースをキャッチアップ', '通勤中・運動中に情報収集', '出典付きで信頼性を確認可能', 'ポッドキャスト配信で収益化も可能'],
    tags: ['Perplexity', 'ElevenLabs', '音声ニュース', 'ポッドキャスト', '情報収集'],
  },
  {
    id: 'combo-6',
    slug: 'elevenlabs-x-heygen',
    title: 'ElevenLabs × HeyGen｜プロ品質の音声付きアバター動画',
    description: 'ElevenLabsの高品質音声とHeyGenのアバターを組み合わせ。HeyGen標準音声より自然なナレーション動画を制作。',
    longDescription: 'ElevenLabsの高品質AI音声とHeyGenのリアルなAIアバターを組み合わせることで、プロ品質のトーキングヘッド動画を完全自動で制作できます。ElevenLabsで感情豊かなナレーション音声を生成し、それをHeyGenのアバターにリップシンクさせれば、まるで実際の人物が話しているかのような動画が完成します。この組み合わせの最大のメリットは、音声とアバターの両方を細かくカスタマイズできる点です。ElevenLabsで声質やスピード、感情を調整し、HeyGenでアバターの外見や背景を設定することで、ブランドに完全にマッチした動画を制作できます。企業のプロモーション動画、Eラーニング教材、多言語対応のカスタマーサポート動画など、活用範囲は非常に広いです。月額約35ドルで運用可能です。',
    toolA: 'ElevenLabs',
    toolASlug: 'elevenlabs',
    toolB: 'HeyGen',
    toolBSlug: 'heygen',
    category: '音声 × 動画',
    useCase: '企業PR・商品紹介・eラーニング・多言語動画',
    steps: [
      { step: 1, action: '台本を準備', tool: 'テキストエディタ', description: '動画で話す内容の台本を作成' },
      { step: 2, action: '高品質音声を生成', tool: 'ElevenLabs', description: '台本からプロ品質のナレーション音声を生成' },
      { step: 3, action: 'アバター動画に合成', tool: 'HeyGen', description: '音声ファイルをアップロードし、アバターの口の動きを同期' },
      { step: 4, action: '動画を書き出し', tool: 'HeyGen', description: 'MP4でダウンロードして各媒体に配信' },
    ],
    benefits: ['HeyGen標準より自然な音声品質', 'ElevenLabsの声クローン機能が使える', 'アバターのリップシンクが自然', '多言語展開が簡単'],
    tags: ['ElevenLabs', 'HeyGen', 'アバター動画', '高品質音声', '企業動画'],
  },
  {
    id: 'combo-7',
    slug: 'chatgpt-x-elevenlabs',
    title: 'ChatGPT × ElevenLabs｜AI台本からプロ音声を一気に作る',
    description: 'ChatGPTで台本を自動生成し、ElevenLabsで即座にナレーション化。YouTube・ポッドキャスト・教材に。',
    longDescription: 'ChatGPTの文章生成力とElevenLabsの音声合成を組み合わせることで、台本作成からナレーション音声の生成までをワンストップで行えます。ChatGPTでターゲット層に合わせた台本を作成し、ElevenLabsでプロ品質の音声に変換するという流れは、YouTube動画、ポッドキャスト、オーディオブック、企業のナレーション付きプレゼンなど、あらゆる音声コンテンツに応用できます。ChatGPTに台本を書かせる際は、話し言葉で書くこと、適切な間を指示すること、感情の変化をテキストに反映させることがポイントです。ElevenLabsはこうしたニュアンスを音声に反映する能力が高く、読み上げというよりもナレーションとして自然な仕上がりになります。月額約25ドルで始められ、1本のナレーション制作が約20分で完了します。',
    toolA: 'ChatGPT',
    toolASlug: 'chatgpt',
    toolB: 'ElevenLabs',
    toolBSlug: 'elevenlabs',
    category: 'テキスト × 音声',
    useCase: 'YouTube動画・ポッドキャスト・教育教材・オーディオブック',
    steps: [
      { step: 1, action: '台本を自動生成', tool: 'ChatGPT', description: 'テーマを入力して構成付きの台本を生成' },
      { step: 2, action: '台本を調整', tool: 'ChatGPT', description: '読み上げ向けに文体・間の取り方を調整' },
      { step: 3, action: 'ナレーション生成', tool: 'ElevenLabs', description: '台本テキストから高品質音声を生成' },
      { step: 4, action: '音声を活用', tool: '各プラットフォーム', description: '動画編集ソフトに組み込む、またはポッドキャストとして配信' },
    ],
    benefits: ['台本作成から音声生成まで15分', '声出し不要・収録環境不要', '何度でもリテイク可能', '多言語対応で海外展開'],
    tags: ['ChatGPT', 'ElevenLabs', '台本', 'ナレーション', 'YouTube'],
  },
  {
    id: 'combo-8',
    slug: 'chatgpt-x-heygen',
    title: 'ChatGPT × HeyGen｜台本生成からアバター動画まで完全自動',
    description: 'ChatGPTで台本を書きHeyGenでアバター動画化。企業紹介・商品PR・教育動画を顔出しなしで大量制作。',
    longDescription: 'ChatGPTで作成した台本をHeyGenのAIアバターに話させるこの組み合わせは、顔出しなしで人が話すプレゼンテーション動画を量産するのに最適です。ChatGPTは視聴者を引き込む構成の台本作成が得意で、フックから結論までの流れを論理的に組み立ててくれます。HeyGenはその台本をリアルなアバターが自然な表情と口の動きで話す動画に変換します。自分の顔写真からカスタムアバターを作れば、自分の分身が24時間働いてくれるような感覚でコンテンツを量産できます。商品紹介、オンライン講座、企業の社内コミュニケーション、SNS用のショート動画など、用途は多岐にわたります。台本作成から動画出力まで約30分で完了し、月額約30ドルで運用可能。動画マーケティングのハードルを大幅に下げる組み合わせです。',
    toolA: 'ChatGPT',
    toolASlug: 'chatgpt',
    toolB: 'HeyGen',
    toolBSlug: 'heygen',
    category: 'テキスト × 動画',
    useCase: '企業紹介・商品PR・社内研修・多言語対応',
    steps: [
      { step: 1, action: '台本を生成', tool: 'ChatGPT', description: '目的・ターゲットを指定して2〜3分の台本を生成' },
      { step: 2, action: 'HeyGenに台本入力', tool: 'HeyGen', description: 'アバター・背景・声を選び、台本テキストを入力' },
      { step: 3, action: '動画を生成', tool: 'HeyGen', description: 'AIが自動で口の動き・ジェスチャーを合成' },
      { step: 4, action: '動画を活用', tool: '各プラットフォーム', description: 'SNS・Webサイト・社内ポータルに展開' },
    ],
    benefits: ['撮影・編集スキル完全不要', '1本20分で完成', '100以上のアバターから選択', '40言語以上に対応'],
    tags: ['ChatGPT', 'HeyGen', 'アバター動画', '企業PR', '自動化'],
  },
  {
    id: 'combo-9',
    slug: 'canva-x-elevenlabs',
    title: 'Canva × ElevenLabs｜デザイン+ナレーションで動画広告を作る',
    description: 'Canvaで動画デザインを作り、ElevenLabsのナレーションを追加。プロ級の動画広告をノーコードで制作。',
    longDescription: 'Canva AIのビジュアル制作力とElevenLabsの音声生成を組み合わせることで、スライドショー動画やプレゼン動画を効率的に制作できます。Canvaでスライドやインフォグラフィックを作成し、ElevenLabsでスライドの内容を解説するナレーション音声を生成、最終的にCanvaの動画編集機能で映像と音声を合体させます。この組み合わせは、教育コンテンツ、企業の研修動画、製品説明動画、SNS用の解説動画など、ビジュアルとナレーションの両方が必要なコンテンツに最適です。Canvaのテンプレートを使えばデザインの知識がなくても美しいスライドが作れ、ElevenLabsの自然な音声がプロフェッショナルな印象を与えます。1本あたり約40分で制作でき、月額約18ドルで運用可能。デザイナーやナレーターを雇う予算がない個人や中小企業にとって、強力なコンテンツ制作ソリューションです。',
    toolA: 'Canva',
    toolASlug: 'canva-ai',
    toolB: 'ElevenLabs',
    toolBSlug: 'elevenlabs',
    category: 'デザイン × 音声',
    useCase: '動画広告・SNS動画・プロモーション・教材',
    steps: [
      { step: 1, action: '動画テンプレを選択', tool: 'Canva', description: 'SNS広告・プレゼン等の動画テンプレートを選択' },
      { step: 2, action: 'デザインを編集', tool: 'Canva', description: 'テキスト・画像・アニメーションをカスタマイズ' },
      { step: 3, action: 'ナレーションを生成', tool: 'ElevenLabs', description: '動画の内容に合わせたナレーション音声を生成' },
      { step: 4, action: '音声を合成して書き出し', tool: 'Canva', description: 'ナレーション音声をCanva動画にインポートして完成' },
    ],
    benefits: ['デザイナー不要でプロ級動画', 'テンプレートで制作時間を短縮', 'ナレーション追加で訴求力アップ', 'SNS各サイズに自動リサイズ'],
    tags: ['Canva', 'ElevenLabs', '動画広告', 'SNS動画', 'ノーコード'],
  },
  {
    id: 'combo-10',
    slug: 'manus-x-notion',
    title: 'Manus × Notion｜AIエージェントの調査結果を自動蓄積',
    description: 'Manusに調査タスクを丸投げし、結果をNotionに自動整理。定型リサーチを完全自動化して知識を蓄積。',
    longDescription: 'ManusのAIエージェント機能とNotionのナレッジ管理を組み合わせることで、調査作業を完全に自動化できます。Manusは指示を与えるだけでWebを自動巡回し、情報の収集・分析・レポート化までを自律的に実行するAIエージェントです。生成されたレポートをNotionデータベースに保存すれば、過去の調査結果を横断検索でき、組織の知識資産として蓄積されていきます。競合調査、市場動向レポート、技術トレンドの定期調査など、繰り返し発生するリサーチ業務にこの組み合わせは絶大な効果を発揮します。Manusのスケジュール実行機能を使えば、毎週月曜日に自動で調査を実行し、Notionに結果を保存するといった完全自動化も可能です。人間の作業時間はほぼゼロで、調査の質と頻度を大幅に向上させられます。',
    toolA: 'Manus',
    toolASlug: 'manus',
    toolB: 'Notion',
    toolBSlug: 'notion',
    category: 'エージェント × 整理',
    useCase: '競合調査・市場分析・定期レポート・情報監視',
    steps: [
      { step: 1, action: '調査タスクを指示', tool: 'Manus', description: '「○○業界の最新動向を調査して」とテキストで指示' },
      { step: 2, action: 'AIが自律的に調査', tool: 'Manus', description: 'AIがWebを自動巡回し、情報を収集・分析・レポート化' },
      { step: 3, action: '成果物を確認', tool: 'Manus', description: '生成されたレポートの内容を確認・修正指示' },
      { step: 4, action: 'Notionに保存・整理', tool: 'Notion', description: 'レポートをNotionデータベースに保存しチームに共有' },
    ],
    benefits: ['調査作業を完全自動化', '人間の作業時間ゼロでレポート完成', 'スケジュール実行で定期調査も可能', 'Notionで過去の調査を横断検索'],
    tags: ['Manus', 'Notion', 'AIエージェント', '自動調査', '競合分析'],
  },
];

export function getAllCombinations(): ToolCombination[] {
  return combinations;
}

export function getCombinationBySlug(slug: string): ToolCombination | undefined {
  return combinations.find(c => c.slug === slug);
}
