import { ToolCombination } from '@/types';

const combinations: ToolCombination[] = [
  {
    id: 'combo-1',
    slug: 'genspark-x-notion',
    title: 'Genspark × Notion｜AIリサーチ結果を自動で整理する方法',
    description: 'Gensparkで深掘りリサーチした情報をNotionに整理。情報収集から知識管理まで一気通貫のワークフローを構築。',
    toolA: 'Genspark',
    toolASlug: 'genspark',
    toolB: 'Notion',
    toolBSlug: 'notion',
    category: 'リサーチ × 整理',
    useCase: '市場調査・競合分析・学習ノート作成',
    steps: [
      { step: 1, action: 'Gensparkでリサーチ', tool: 'Genspark', description: 'テーマを入力してSuper Agentが複数ソースから情報を収集・要約' },
      { step: 2, action: 'リサーチ結果をコピー', tool: 'Genspark', description: '生成されたレポートのテキスト・リンクをコピー' },
      { step: 3, action: 'Notionに構造化して保存', tool: 'Notion', description: 'データベースに日付・テーマ・要約・ソースURLを記録' },
      { step: 4, action: 'Notionで分析・共有', tool: 'Notion', description: 'フィルタ・ビューで情報を整理しチームに共有' },
    ],
    benefits: ['リサーチ時間を1/3に短縮', '情報の散逸を防止', 'チームでの知識共有が簡単', 'ソースURL付きで信頼性を担保'],
    tags: ['Genspark', 'Notion', 'リサーチ', '情報整理', 'ナレッジ管理'],
  },
  {
    id: 'combo-2',
    slug: 'genspark-x-elevenlabs',
    title: 'Genspark × ElevenLabs｜AIリサーチからナレーション動画を作る',
    description: 'Gensparkで調べた内容をElevenLabsで音声化。解説動画やポッドキャストのコンテンツ制作を自動化。',
    toolA: 'Genspark',
    toolASlug: 'genspark',
    toolB: 'ElevenLabs',
    toolBSlug: 'elevenlabs',
    category: 'リサーチ × 音声',
    useCase: '解説動画・ポッドキャスト・教育コンテンツ',
    steps: [
      { step: 1, action: 'テーマをリサーチ', tool: 'Genspark', description: 'トピックについて包括的な情報を収集' },
      { step: 2, action: '台本に変換', tool: 'Genspark', description: 'リサーチ結果を読み上げ用の台本形式に変換' },
      { step: 3, action: 'ナレーション生成', tool: 'ElevenLabs', description: '台本をElevenLabsに貼り付けて自然な音声を生成' },
      { step: 4, action: '音声を活用', tool: '動画編集ツール', description: '生成した音声を動画やポッドキャストに組み込む' },
    ],
    benefits: ['リサーチから音声まで30分で完成', '声出し不要でコンテンツ制作', '多言語対応で海外展開可能', '一貫した声質でブランディング'],
    tags: ['Genspark', 'ElevenLabs', 'ナレーション', '解説動画', 'ポッドキャスト'],
  },
  {
    id: 'combo-3',
    slug: 'genspark-x-heygen',
    title: 'Genspark × HeyGen｜リサーチからAIアバター動画を自動生成',
    description: 'Gensparkで情報収集、HeyGenでアバター動画に変換。企業紹介・教育コンテンツをAIだけで制作。',
    toolA: 'Genspark',
    toolASlug: 'genspark',
    toolB: 'HeyGen',
    toolBSlug: 'heygen',
    category: 'リサーチ × 動画',
    useCase: '企業紹介動画・教育コンテンツ・プレゼン動画',
    steps: [
      { step: 1, action: '内容をリサーチ', tool: 'Genspark', description: '動画のテーマについて包括的に調査' },
      { step: 2, action: '台本を作成', tool: 'Genspark', description: 'リサーチ結果から2〜3分の台本を生成' },
      { step: 3, action: 'アバター動画を生成', tool: 'HeyGen', description: '台本を入力しアバター・背景を選んで動画生成' },
      { step: 4, action: '動画を書き出し', tool: 'HeyGen', description: 'MP4でダウンロードして各プラットフォームに投稿' },
    ],
    benefits: ['顔出し不要で動画制作', '撮影・編集スキル不要', '多言語アバターで海外展開', '1本あたり20分で完成'],
    tags: ['Genspark', 'HeyGen', 'アバター動画', 'AI動画', '企業動画'],
  },
  {
    id: 'combo-4',
    slug: 'perplexity-x-notion',
    title: 'Perplexity × Notion｜出典付きリサーチを知識データベース化',
    description: 'Perplexityの出典付き検索結果をNotionに蓄積。信頼性の高い情報をチームで共有できる知識基盤を構築。',
    toolA: 'Perplexity',
    toolASlug: 'perplexity',
    toolB: 'Notion',
    toolBSlug: 'notion',
    category: 'リサーチ × 整理',
    useCase: '学術リサーチ・ビジネスインテリジェンス・チーム知識共有',
    steps: [
      { step: 1, action: '出典付きで検索', tool: 'Perplexity', description: 'Pro Searchで質問し、出典リンク付きの回答を取得' },
      { step: 2, action: '回答を整理', tool: 'Perplexity', description: 'フォローアップ質問で深掘りし、必要な情報を網羅' },
      { step: 3, action: 'Notionに構造化保存', tool: 'Notion', description: 'テーマ・要約・出典URL・日付をデータベースに記録' },
      { step: 4, action: 'ナレッジベースとして活用', tool: 'Notion', description: 'タグ・フィルタで横断検索し、レポートや記事に活用' },
    ],
    benefits: ['全情報に出典が付いて信頼性が高い', 'リサーチの再現性を確保', 'チーム全員が同じ情報にアクセス', '過去のリサーチを即座に検索可能'],
    tags: ['Perplexity', 'Notion', '出典付き', 'ナレッジベース', 'チーム共有'],
  },
  {
    id: 'combo-5',
    slug: 'perplexity-x-elevenlabs',
    title: 'Perplexity × ElevenLabs｜最新情報を音声ニュースに変換',
    description: 'Perplexityで最新ニュースを要約し、ElevenLabsで音声化。通勤中に聴けるパーソナルニュースを毎朝自動生成。',
    toolA: 'Perplexity',
    toolASlug: 'perplexity',
    toolB: 'ElevenLabs',
    toolBSlug: 'elevenlabs',
    category: 'リサーチ × 音声',
    useCase: '音声ニュース・ポッドキャスト・情報キャッチアップ',
    steps: [
      { step: 1, action: '最新ニュースを収集', tool: 'Perplexity', description: '業界の最新ニュースを検索し要約を取得' },
      { step: 2, action: '読み上げ台本に変換', tool: 'Perplexity', description: '要約を3〜5分の読み上げ用テキストに整形' },
      { step: 3, action: '音声を生成', tool: 'ElevenLabs', description: '台本から自然な音声ファイルを生成' },
      { step: 4, action: '音声を配信', tool: 'Spotify等', description: 'ポッドキャストとして配信、または個人で聴取' },
    ],
    benefits: ['毎朝5分で業界ニュースをキャッチアップ', '通勤中・運動中に情報収集', '出典付きで信頼性を確認可能', 'ポッドキャスト配信で収益化も可能'],
    tags: ['Perplexity', 'ElevenLabs', '音声ニュース', 'ポッドキャスト', '情報収集'],
  },
  {
    id: 'combo-6',
    slug: 'elevenlabs-x-heygen',
    title: 'ElevenLabs × HeyGen｜プロ品質の音声付きアバター動画',
    description: 'ElevenLabsの高品質音声とHeyGenのアバターを組み合わせ。HeyGen標準音声より自然なナレーション動画を制作。',
    toolA: 'ElevenLabs',
    toolASlug: 'elevenlabs',
    toolB: 'HeyGen',
    toolBSlug: 'heygen',
    category: '音声 × 動画',
    useCase: '企業PR・商品紹介・eラーニング・多言語動画',
    steps: [
      { step: 1, action: '台本を準備', tool: 'テキストエディタ', description: '動画で話す内容の台本を作成' },
      { step: 2, action: '高品質音声を生成', tool: 'ElevenLabs', description: '台本からプロ品質のナレーション音声を生成' },
      { step: 3, action: 'アバター動画に合成', tool: 'HeyGen', description: '音声ファイルをアップロードし、アバターの口の動きを同期' },
      { step: 4, action: '動画を書き出し', tool: 'HeyGen', description: 'MP4でダウンロードして各媒体に配信' },
    ],
    benefits: ['HeyGen標準より自然な音声品質', 'ElevenLabsの声クローン機能が使える', 'アバターのリップシンクが自然', '多言語展開が簡単'],
    tags: ['ElevenLabs', 'HeyGen', 'アバター動画', '高品質音声', '企業動画'],
  },
  {
    id: 'combo-7',
    slug: 'chatgpt-x-elevenlabs',
    title: 'ChatGPT × ElevenLabs｜AI台本からプロ音声を一気に作る',
    description: 'ChatGPTで台本を自動生成し、ElevenLabsで即座にナレーション化。YouTube・ポッドキャスト・教材に。',
    toolA: 'ChatGPT',
    toolASlug: 'chatgpt',
    toolB: 'ElevenLabs',
    toolBSlug: 'elevenlabs',
    category: 'テキスト × 音声',
    useCase: 'YouTube動画・ポッドキャスト・教育教材・オーディオブック',
    steps: [
      { step: 1, action: '台本を自動生成', tool: 'ChatGPT', description: 'テーマを入力して構成付きの台本を生成' },
      { step: 2, action: '台本を調整', tool: 'ChatGPT', description: '読み上げ向けに文体・間の取り方を調整' },
      { step: 3, action: 'ナレーション生成', tool: 'ElevenLabs', description: '台本テキストから高品質音声を生成' },
      { step: 4, action: '音声を活用', tool: '各プラットフォーム', description: '動画編集ソフトに組み込む、またはポッドキャストとして配信' },
    ],
    benefits: ['台本作成から音声生成まで15分', '声出し不要・収録環境不要', '何度でもリテイク可能', '多言語対応で海外展開'],
    tags: ['ChatGPT', 'ElevenLabs', '台本', 'ナレーション', 'YouTube'],
  },
  {
    id: 'combo-8',
    slug: 'chatgpt-x-heygen',
    title: 'ChatGPT × HeyGen｜台本生成からアバター動画まで完全自動',
    description: 'ChatGPTで台本を書きHeyGenでアバター動画化。企業紹介・商品PR・教育動画を顔出しなしで大量制作。',
    toolA: 'ChatGPT',
    toolASlug: 'chatgpt',
    toolB: 'HeyGen',
    toolBSlug: 'heygen',
    category: 'テキスト × 動画',
    useCase: '企業紹介・商品PR・社内研修・多言語対応',
    steps: [
      { step: 1, action: '台本を生成', tool: 'ChatGPT', description: '目的・ターゲットを指定して2〜3分の台本を生成' },
      { step: 2, action: 'HeyGenに台本入力', tool: 'HeyGen', description: 'アバター・背景・声を選び、台本テキストを入力' },
      { step: 3, action: '動画を生成', tool: 'HeyGen', description: 'AIが自動で口の動き・ジェスチャーを合成' },
      { step: 4, action: '動画を活用', tool: '各プラットフォーム', description: 'SNS・Webサイト・社内ポータルに展開' },
    ],
    benefits: ['撮影・編集スキル完全不要', '1本20分で完成', '100以上のアバターから選択', '40言語以上に対応'],
    tags: ['ChatGPT', 'HeyGen', 'アバター動画', '企業PR', '自動化'],
  },
  {
    id: 'combo-9',
    slug: 'canva-x-elevenlabs',
    title: 'Canva × ElevenLabs｜デザイン+ナレーションで動画広告を作る',
    description: 'Canvaで動画デザインを作り、ElevenLabsのナレーションを追加。プロ級の動画広告をノーコードで制作。',
    toolA: 'Canva',
    toolASlug: 'canva-ai',
    toolB: 'ElevenLabs',
    toolBSlug: 'elevenlabs',
    category: 'デザイン × 音声',
    useCase: '動画広告・SNS動画・プロモーション・教材',
    steps: [
      { step: 1, action: '動画テンプレを選択', tool: 'Canva', description: 'SNS広告・プレゼン等の動画テンプレートを選択' },
      { step: 2, action: 'デザインを編集', tool: 'Canva', description: 'テキスト・画像・アニメーションをカスタマイズ' },
      { step: 3, action: 'ナレーションを生成', tool: 'ElevenLabs', description: '動画の内容に合わせたナレーション音声を生成' },
      { step: 4, action: '音声を合成して書き出し', tool: 'Canva', description: 'ナレーション音声をCanva動画にインポートして完成' },
    ],
    benefits: ['デザイナー不要でプロ級動画', 'テンプレートで制作時間を短縮', 'ナレーション追加で訴求力アップ', 'SNS各サイズに自動リサイズ'],
    tags: ['Canva', 'ElevenLabs', '動画広告', 'SNS動画', 'ノーコード'],
  },
  {
    id: 'combo-10',
    slug: 'manus-x-notion',
    title: 'Manus × Notion｜AIエージェントの調査結果を自動蓄積',
    description: 'Manusに調査タスクを丸投げし、結果をNotionに自動整理。定型リサーチを完全自動化して知識を蓄積。',
    toolA: 'Manus',
    toolASlug: 'manus',
    toolB: 'Notion',
    toolBSlug: 'notion',
    category: 'エージェント × 整理',
    useCase: '競合調査・市場分析・定期レポート・情報監視',
    steps: [
      { step: 1, action: '調査タスクを指示', tool: 'Manus', description: '「○○業界の最新動向を調査して」とテキストで指示' },
      { step: 2, action: 'AIが自律的に調査', tool: 'Manus', description: 'AIがWebを自動巡回し、情報を収集・分析・レポート化' },
      { step: 3, action: '成果物を確認', tool: 'Manus', description: '生成されたレポートの内容を確認・修正指示' },
      { step: 4, action: 'Notionに保存・整理', tool: 'Notion', description: 'レポートをNotionデータベースに保存しチームに共有' },
    ],
    benefits: ['調査作業を完全自動化', '人間の作業時間ゼロでレポート完成', 'スケジュール実行で定期調査も可能', 'Notionで過去の調査を横断検索'],
    tags: ['Manus', 'Notion', 'AIエージェント', '自動調査', '競合分析'],
  },
];

export function getAllCombinations(): ToolCombination[] {
  return combinations;
}

export function getCombinationBySlug(slug: string): ToolCombination | undefined {
  return combinations.find(c => c.slug === slug);
}
