import { ToolComparison } from '@/types';

const comparisons: ToolComparison[] = [
  {
    id: 'cmp-1',
    slug: 'genspark-vs-perplexity',
    title: 'Genspark vs Perplexity｜AI検索エンジン徹底比較',
    description: 'AI検索の二大巨頭を7つの観点で比較。検索精度、引用の信頼性、無料プランの範囲、マルチモーダル対応など、用途別にどちらが最適かを解説します。',
    toolA: 'Genspark',
    toolASlug: 'genspark',
    toolB: 'Perplexity',
    toolBSlug: 'perplexity',
    category: 'AI検索',
    points: [
      { category: '検索精度', toolA: '複数ソースをSparkpageに統合。広範な情報を一画面で提示', toolB: '単一回答に集約し引用リンクを明示。有効リンク率97%', winner: 'B' },
      { category: '無料プラン', toolA: '基本機能は無料で無制限に利用可能', toolB: '1日5回のPro検索が無料。それ以上は月$20', winner: 'A' },
      { category: 'マルチモーダル', toolA: '画像生成・旅行プラン・比較表など多機能', toolB: 'テキスト検索中心。画像理解は限定的', winner: 'A' },
      { category: '回答の深さ', toolA: 'Sparkpageで複数セクションに分けて詳細解説', toolB: '簡潔な回答+ソースリンクで自分で深掘り', winner: 'A' },
      { category: '引用信頼性', toolA: '有効リンク率91%。ペイウォール先を含む場合あり', toolB: '有効リンク率97%。信頼性の高いソースを優先', winner: 'B' },
      { category: 'API/開発者向け', toolA: 'API提供なし（2025年時点）', toolB: 'APIあり。開発者がアプリに検索機能を組み込める', winner: 'B' },
      { category: '日本語対応', toolA: '日本語での検索・回答に対応', toolB: '日本語対応だが英語ソース優先の傾向あり', winner: 'A' },
    ],
    verdict: '無料で幅広く使いたいならGenspark、引用の正確さとAPI連携を重視するならPerplexity。日本語コンテンツのリサーチにはGensparkの方が情報量が多い傾向があります。',
    toolAStrengths: ['無料で無制限利用', 'Sparkpageによる情報の自動整理', 'マルチモーダル対応（画像生成等）', '日本語コンテンツに強い'],
    toolBStrengths: ['引用リンクの信頼性が高い', 'API提供で開発連携可能', '簡潔で的確な回答', 'Pro Searchで深い分析'],
    tags: ['Genspark', 'Perplexity', 'AI検索', '比較', '無料'],
  },
  {
    id: 'cmp-2',
    slug: 'chatgpt-vs-claude',
    title: 'ChatGPT vs Claude｜AIチャット2強を徹底比較',
    description: 'OpenAIのChatGPTとAnthropicのClaudeを比較。文章力、コーディング、分析力、安全性など実用面で差が出るポイントを解説。',
    toolA: 'ChatGPT',
    toolASlug: 'chatgpt',
    toolB: 'Claude',
    toolBSlug: 'claude',
    category: 'AIチャット',
    points: [
      { category: '文章作成', toolA: '汎用的で安定した文章生成。多様なトーンに対応', toolB: '自然で人間味のある文体。長文の一貫性が高い', winner: 'B' },
      { category: 'コーディング', toolA: 'GPT-4oで高精度。プラグインでコード実行も可能', toolB: 'Claude Opus系はコード品質が高く、Artifactsで即プレビュー', winner: 'draw' },
      { category: '長文処理', toolA: '128Kトークン対応。長い文書の要約が得意', toolB: '200Kトークン対応。より長い文書を一度に処理可能', winner: 'B' },
      { category: '機能の幅', toolA: '画像生成(DALL-E)、音声、ブラウジング、プラグイン多数', toolB: 'テキスト/コード中心。画像生成機能は非搭載', winner: 'A' },
      { category: '料金', toolA: '無料プランあり。Plus $20/月', toolB: '無料プランあり。Pro $20/月', winner: 'draw' },
      { category: '安全性', toolA: 'コンテンツフィルタリングあり', toolB: 'Constitutional AIで安全性を重視した設計', winner: 'B' },
    ],
    verdict: 'オールインワンのAIツールとして使うならChatGPT、文章品質とコーディングに特化するならClaude。両方無料プランがあるので試してから決めるのがベスト。',
    toolAStrengths: ['機能の幅が広い（画像生成、音声、プラグイン）', 'ユーザー数最多でコミュニティが充実', 'GPTsでカスタムボット作成可能', 'モバイルアプリの完成度が高い'],
    toolBStrengths: ['自然で読みやすい文章生成', '200Kトークンの長文対応', 'コード品質が高い', 'Artifacts機能でリアルタイムプレビュー'],
    tags: ['ChatGPT', 'Claude', 'AIチャット', '比較', 'コーディング'],
  },
  {
    id: 'cmp-3',
    slug: 'elevenlabs-vs-murf',
    title: 'ElevenLabs vs Murf AI｜AI音声生成ツール比較',
    description: 'AI音声合成の2大ツールを比較。声の自然さ、多言語対応、料金、商用利用の可否など、ナレーション制作に必要な情報を網羅。',
    toolA: 'ElevenLabs',
    toolASlug: 'elevenlabs',
    toolB: 'Murf AI',
    toolBSlug: 'murf-ai',
    category: 'AI音声',
    points: [
      { category: '音声の自然さ', toolA: '感情表現が豊かで人間にかなり近い品質', toolB: 'プロ品質だがやや機械的な印象が残る場合あり', winner: 'A' },
      { category: '多言語対応', toolA: '29言語以上に対応。日本語の品質も高い', toolB: '20言語以上対応。英語が最も高品質', winner: 'A' },
      { category: 'ボイスクローン', toolA: '数分の音声サンプルから高精度にクローン可能', toolB: 'クローン機能はあるが精度はElevenLabsに劣る', winner: 'A' },
      { category: '料金', toolA: '無料プランあり。Starter $5/月〜', toolB: '無料プランあり。Creator $26/月〜', winner: 'A' },
      { category: '使いやすさ', toolA: 'シンプルなUI。テキスト貼り付けですぐ生成', toolB: 'テンプレート付きで初心者に優しいUI', winner: 'draw' },
      { category: '商用利用', toolA: '有料プランで商用利用可', toolB: '有料プランで商用利用可', winner: 'draw' },
    ],
    verdict: '音声品質とボイスクローンを最重視するならElevenLabs一択。コスパを求めつつプロ品質のナレーションが欲しいならMurf AIも選択肢に入る。',
    toolAStrengths: ['業界最高レベルの音声品質', '高精度ボイスクローン', '29言語以上対応', '月$5からの低価格プラン'],
    toolBStrengths: ['テンプレート付きで初心者向け', '130以上のプリセットボイス', '動画編集機能も内蔵', 'チーム向けコラボ機能'],
    tags: ['ElevenLabs', 'Murf AI', 'AI音声', 'ナレーション', '比較'],
  },
  {
    id: 'cmp-4',
    slug: 'notion-ai-vs-obsidian',
    title: 'Notion AI vs Obsidian｜ナレッジ管理ツール比較',
    description: 'AI搭載のNotion AIとプラグインで拡張するObsidianを比較。チーム利用か個人利用か、データの所有権、AI機能の差を解説。',
    toolA: 'Notion AI',
    toolASlug: 'notion-ai',
    toolB: 'Obsidian',
    toolBSlug: 'obsidian',
    category: 'ナレッジ管理',
    points: [
      { category: 'AI機能', toolA: 'Q&A、要約、翻訳、文章生成がネイティブ搭載', toolB: 'プラグインでAI機能追加。APIキー設定が必要', winner: 'A' },
      { category: 'データ保存', toolA: 'クラウド保存。Notionのサーバーに依存', toolB: 'ローカル保存（Markdownファイル）。完全に自分の管理下', winner: 'B' },
      { category: 'チーム利用', toolA: 'リアルタイム共同編集、権限管理、コメント機能', toolB: '基本は個人向け。共有にはObsidian Publishが必要', winner: 'A' },
      { category: 'カスタマイズ', toolA: 'テンプレート豊富だがUI変更は限定的', toolB: 'プラグイン・テーマで無限にカスタマイズ可能', winner: 'B' },
      { category: '料金', toolA: '無料プランあり。AI機能は$10/月追加', toolB: '個人利用は無料。商用$50/年', winner: 'B' },
      { category: 'モバイル対応', toolA: 'iOS/Android対応。同期も高速', toolB: 'iOS/Androidあり。同期にはObsidian Syncが別途必要', winner: 'A' },
    ],
    verdict: 'チームでの情報共有とAI機能をすぐ使いたいならNotion AI。データの所有権を保ちつつ自由にカスタマイズしたいならObsidian。',
    toolAStrengths: ['AI機能がネイティブ搭載で設定不要', 'チームコラボレーションが強力', 'データベース機能でタスク管理も可能', 'モバイル同期がスムーズ'],
    toolBStrengths: ['データが完全にローカル（プライバシー重視）', 'プラグインで無限拡張', 'Markdownベースで他ツール移行が容易', '個人利用は完全無料'],
    tags: ['Notion AI', 'Obsidian', 'ナレッジ管理', 'メモ', '比較'],
  },
  {
    id: 'cmp-5',
    slug: 'canva-ai-vs-adobe-firefly',
    title: 'Canva AI vs Adobe Firefly｜AIデザインツール比較',
    description: '手軽さのCanva AIとプロ品質のAdobe Fireflyを比較。SNS投稿、サムネイル、広告バナーなど用途別のおすすめを解説。',
    toolA: 'Canva AI',
    toolASlug: 'canva-ai',
    toolB: 'Adobe Firefly',
    toolBSlug: 'adobe-firefly',
    category: 'AIデザイン',
    points: [
      { category: '使いやすさ', toolA: 'テンプレート選んで編集するだけ。初心者でも5分で完成', toolB: 'Adobe製品の知識があると有利。学習コストあり', winner: 'A' },
      { category: 'AI画像生成', toolA: 'テキストから画像生成可能。品質は中程度', toolB: '商用利用可能な高品質画像を生成。著作権クリア', winner: 'B' },
      { category: 'テンプレート数', toolA: '数十万のテンプレート。SNS用が特に豊富', toolB: 'テンプレートは少なめ。ゼロから作る前提', winner: 'A' },
      { category: '商用利用', toolA: 'Pro($12.99/月)で商用利用可', toolB: '生成画像は商用利用可。著作権補償あり', winner: 'B' },
      { category: 'チーム機能', toolA: 'ブランドキット、リアルタイム共同編集あり', toolB: 'Creative Cloudライブラリで素材共有', winner: 'A' },
      { category: '料金', toolA: '無料プランあり。Pro $12.99/月', toolB: '無料枠あり。Creative Cloud $7,780/年〜', winner: 'A' },
    ],
    verdict: 'SNS投稿やサムネイルを手早く量産するならCanva AI。プロ品質のオリジナル画像を商用利用したいならAdobe Firefly。',
    toolAStrengths: ['直感的なUIで学習コストゼロ', 'テンプレート数十万種', '無料プランでも十分使える', 'チームコラボ機能が充実'],
    toolBStrengths: ['商用利用の著作権がクリア', 'Photoshop/Illustratorと完全連携', '高品質なAI画像生成', 'プロ向けの細かい調整が可能'],
    tags: ['Canva AI', 'Adobe Firefly', 'AIデザイン', '画像生成', '比較'],
  },
  {
    id: 'cmp-6',
    slug: 'invideo-vs-pictory',
    title: 'InVideo AI vs Pictory｜AI動画生成ツール比較',
    description: 'テキストから動画を自動生成する2大ツールを比較。YouTube用、SNS用、顔出しなしなど、制作スタイル別のおすすめを解説。',
    toolA: 'InVideo AI',
    toolASlug: 'invideo-ai',
    toolB: 'Pictory',
    toolBSlug: 'pictory',
    category: 'AI動画',
    points: [
      { category: '動画生成速度', toolA: 'テキスト入力から5-10分で完成', toolB: '台本+音声から10-15分で完成', winner: 'A' },
      { category: 'テンプレート', toolA: '5000以上のテンプレート。多様なジャンルに対応', toolB: 'テンプレートは控えめ。台本ベースの生成が中心', winner: 'A' },
      { category: '字幕自動生成', toolA: 'AI字幕あり。スタイル変更可能', toolB: '字幕生成に特化。精度が高い', winner: 'B' },
      { category: 'ブログ→動画', toolA: 'URL入力で動画化可能', toolB: 'ブログURL入力で自動動画化。この用途に特化', winner: 'B' },
      { category: '料金', toolA: '無料プランあり。Business $30/月', toolB: '無料トライアルあり。Starter $23/月', winner: 'B' },
      { category: '日本語対応', toolA: '日本語テキスト入力で動画生成可能', toolB: '日本語対応だが英語の方が品質が高い', winner: 'A' },
    ],
    verdict: 'テンプレートから手早く動画を作りたいならInVideo AI。ブログ記事の動画化や字幕付き動画に特化するならPictory。',
    toolAStrengths: ['5000以上のテンプレート', 'テキスト入力だけで完成する手軽さ', '日本語動画の生成品質が高い', '無料プランで試せる'],
    toolBStrengths: ['ブログ→動画変換に特化', '字幕生成の精度が高い', '月$23からのコスパ', '長尺動画の自動要約機能'],
    tags: ['InVideo AI', 'Pictory', 'AI動画', '動画生成', '比較'],
  },
  {
    id: 'cmp-7',
    slug: 'heygen-vs-synthesia',
    title: 'HeyGen vs Synthesia｜AIアバター動画ツール比較',
    description: 'AIアバターが話す動画を生成する2大サービスを比較。アバターの品質、多言語対応、料金体系の違いを解説。',
    toolA: 'HeyGen',
    toolASlug: 'heygen',
    toolB: 'Synthesia',
    toolBSlug: 'synthesia',
    category: 'AIアバター',
    points: [
      { category: 'アバター品質', toolA: 'リアルな表情と口の動き。自然さは業界トップクラス', toolB: '安定した品質。やや人形的だが改善中', winner: 'A' },
      { category: 'カスタムアバター', toolA: '自分の顔からアバター作成可能（数分の動画でOK）', toolB: 'カスタムアバター作成可能（撮影が必要）', winner: 'A' },
      { category: '多言語対応', toolA: '40以上の言語に対応。リップシンクも自動', toolB: '120以上の言語に対応', winner: 'B' },
      { category: 'テンプレート', toolA: 'プリセットシーン多数', toolB: '企業研修用テンプレートが充実', winner: 'B' },
      { category: '料金', toolA: 'Creator $29/月〜', toolB: 'Starter $29/月〜', winner: 'draw' },
      { category: '企業向け機能', toolA: 'API提供。個人〜中規模向き', toolB: 'SCORM対応、LMS連携。大企業の研修に強い', winner: 'B' },
    ],
    verdict: 'リアルなアバター品質を求めるクリエイターにはHeyGen。企業研修やeラーニング用途にはSynthesia。',
    toolAStrengths: ['業界最高のアバターリアルさ', '自分の顔アバターが簡単に作れる', 'APIで開発連携可能', '個人クリエイター向けプランあり'],
    toolBStrengths: ['120言語以上の多言語対応', '企業研修テンプレートが充実', 'SCORM/LMS連携', '大企業での導入実績多数'],
    tags: ['HeyGen', 'Synthesia', 'AIアバター', '動画生成', '比較'],
  },
  {
    id: 'cmp-8',
    slug: 'midjourney-vs-stable-diffusion',
    title: 'Midjourney vs Stable Diffusion｜AI画像生成比較',
    description: 'AI画像生成の2大ツールを比較。アート品質、カスタマイズ性、料金、商用利用の条件など、クリエイターが知るべきポイントを解説。',
    toolA: 'Midjourney',
    toolASlug: 'midjourney',
    toolB: 'Stable Diffusion',
    toolBSlug: 'stable-diffusion',
    category: 'AI画像生成',
    points: [
      { category: '画像品質', toolA: 'アート寄りの美しい画像。デフォルトで高品質', toolB: '設定次第で高品質。モデル選びが重要', winner: 'A' },
      { category: 'カスタマイズ', toolA: 'プロンプトとパラメータで調整', toolB: 'モデル・LoRA・ControlNetで無限にカスタム可能', winner: 'B' },
      { category: '料金', toolA: '$10/月〜。無料プランなし', toolB: 'オープンソースで無料。ただしGPU環境が必要', winner: 'B' },
      { category: '使いやすさ', toolA: 'Discordまたは公式サイトで手軽に利用', toolB: 'ローカル環境構築が必要。ComfyUIなどで簡略化可', winner: 'A' },
      { category: '商用利用', toolA: '有料プランで商用利用可', toolB: 'ライセンスにより商用利用可。制約が少ない', winner: 'B' },
      { category: 'プライバシー', toolA: '生成画像はデフォルトで公開', toolB: 'ローカル実行なら完全非公開', winner: 'B' },
    ],
    verdict: '手軽に美しい画像を生成したいならMidjourney。自由度とプライバシーを重視し、技術的な調整を楽しめるならStable Diffusion。',
    toolAStrengths: ['デフォルトで高品質なアート画像', '環境構築不要で手軽', 'コミュニティが活発', 'V6でフォトリアル品質も向上'],
    toolBStrengths: ['オープンソースで無料', 'カスタマイズの自由度が無限', 'ローカル実行でプライバシー保護', '商用利用の制約が少ない'],
    tags: ['Midjourney', 'Stable Diffusion', 'AI画像生成', '比較', 'オープンソース'],
  },
];

export function getAllComparisons(): ToolComparison[] {
  return comparisons;
}

export function getComparisonBySlug(slug: string): ToolComparison | undefined {
  return comparisons.find(c => c.slug === slug);
}
