import { Workflow } from '@/types';

export const workflows: Workflow[] = [
  {
    id: 'wf-1',
    title: 'YouTubeの動画を自動で作りたい',
    slug: 'youtube-video-auto-create',
    shortTitle: 'YouTube動画自動作成',
    description: 'ChatGPTで台本を作り、ElevenLabsでナレーション、InVideo AIで映像を自動生成。1本45分、月4,500円でYouTube動画が完成します。',
    timeEstimate: '1本あたり約45分（慣れれば30分）',
    monthlyCost: '$30/月',
    monthlyCostJPY: '約4,500円',
    category: '動画',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '企画・台本を作る', tool: 'ChatGPT', cost: '無料', description: 'テーマを入力するだけで台本が出てくる', nextHint: 'この台本テキストをStep 2のElevenLabsに貼り付ける' },
      { step: 2, action: 'ナレーション音声を作る', tool: 'ElevenLabs', cost: '$5/月〜', description: 'テキストを貼るだけで人間そっくりの声になる', nextHint: '生成した音声mp3をStep 3のInVideoに読み込ませる' },
      { step: 3, action: '映像を自動生成する', tool: 'InVideo AI', cost: '$25/月', description: '台本を入れると映像・字幕・BGM全部入りの動画ができる', nextHint: '書き出した動画をダウンロードしてStep 4へ' },
      { step: 4, action: 'サムネイルを作る', tool: 'Canva', cost: '無料', description: 'テンプレを選んで文字を変えるだけ', nextHint: 'サムネイル画像を保存してStep 5で一緒にアップロード' },
      { step: 5, action: '投稿する', tool: 'YouTube Studio', cost: '無料', description: 'タイトル・説明文もStep1のChatGPTで作れる' },
    ],
    freeAlternatives: [
      { original: 'ElevenLabs', alternative: 'VOICEVOX', note: '日本語対応・完全無料' },
      { original: 'InVideo AI', alternative: 'CapCut', note: '無料・手動編集だが初心者でも使いやすい' },
    ],
    tags: ['YouTube', '動画作成', '自動化', 'AI動画', 'ナレーション'],
    relatedToolSlugs: ['chatgpt', 'elevenlabs', 'invideo', 'canva'],
  },
  {
    id: 'wf-2',
    title: '顔出しなしでYouTubeチャンネルを運営したい',
    slug: 'faceless-youtube-channel',
    shortTitle: '顔出しなしYouTube',
    description: 'TubeBuddyでニッチを分析し、Claudeで台本、ElevenLabsで音声、Pictoryで映像を自動生成。顔出し不要で月5,000円からYouTubeチャンネルを運営できます。',
    timeEstimate: '1本あたり約60分',
    monthlyCost: '$33/月',
    monthlyCostJPY: '約5,000円',
    category: '動画',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: 'ニッチを決める', tool: 'TubeBuddy（無料版）', cost: '無料', description: 'どんなジャンルが伸びてるか数字で見れる' },
      { step: 2, action: '台本を作る', tool: 'Claude', cost: '無料', description: 'シリーズもので一貫性のある台本が得意' },
      { step: 3, action: 'AI音声を作る', tool: 'ElevenLabs', cost: '$5/月〜', description: '自分の声を録音しなくてOK' },
      { step: 4, action: '映像を自動生成する', tool: 'Pictory', cost: '$19/月', description: '台本+音声を入れると素材映像を自動で当ててくれる' },
      { step: 5, action: 'ショート動画も量産する', tool: 'OpusClip', cost: '$9/月', description: '長い動画から短い動画を自動で切り出してくれる' },
    ],
    freeAlternatives: [
      { original: 'Pictory', alternative: 'CapCut + Pexels', note: '無料素材を手動で当てる' },
      { original: 'OpusClip', alternative: 'CapCut', note: 'リサイズ機能で手動カット' },
    ],
    tags: ['YouTube', '顔出しなし', 'フェイスレス', '動画', '自動化'],
    relatedToolSlugs: ['claude', 'elevenlabs', 'pictory', 'opusclip'],
  },
  {
    id: 'wf-3',
    title: 'TikTok/リール用のショート動画を量産したい',
    slug: 'tiktok-reels-short-video',
    shortTitle: 'ショート動画量産',
    description: 'ChatGPTでネタ出し、AutoShorts.aiで自動生成、CapCutで字幕調整、Bufferで全SNSに一括投稿。1本15分、月2,900円でショート動画を量産できます。',
    timeEstimate: '1本あたり約15分',
    monthlyCost: '$19/月',
    monthlyCostJPY: '約2,900円',
    category: '動画',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: 'ネタ・台本を作る', tool: 'ChatGPT', cost: '無料', description: '「バズるショート動画のネタ出して」でOK' },
      { step: 2, action: '動画を自動生成する', tool: 'AutoShorts.ai', cost: '$19/月', description: 'テーマを入れるだけで縦動画が完成する' },
      { step: 3, action: '字幕を調整する', tool: 'CapCut', cost: '無料', description: '自動字幕＋おしゃれなテロップが簡単に作れる' },
      { step: 4, action: '全SNSに一括投稿する', tool: 'Buffer', cost: '無料〜', description: 'TikTok・Instagram・YouTubeに同時投稿できる' },
    ],
    freeAlternatives: [
      { original: 'AutoShorts.ai', alternative: 'CapCut', note: 'テンプレート機能で手動作成' },
    ],
    tags: ['TikTok', 'Reels', 'ショート動画', 'SNS', '量産'],
    relatedToolSlugs: ['chatgpt', 'autoshorts', 'capcut', 'buffer'],
  },
  {
    id: 'wf-4',
    title: 'しゃべるAIアバターで動画を作りたい',
    slug: 'ai-avatar-video',
    shortTitle: 'AIアバター動画',
    description: 'ChatGPTで台本を作り、HeyGenでAIアバターが喋る動画を生成。CapCutで仕上げれば、20分で本格的なアバター動画が完成します。',
    timeEstimate: '1本あたり約20分',
    monthlyCost: '$29/月',
    monthlyCostJPY: '約4,400円',
    category: '動画',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '台本を作る', tool: 'ChatGPT', cost: '無料', description: '話す内容をテキストで準備するだけ' },
      { step: 2, action: 'アバター動画を生成する', tool: 'HeyGen', cost: '$29/月', description: 'テキストを入れるとAIの人物が喋ってくれる' },
      { step: 3, action: '字幕・編集する', tool: 'CapCut', cost: '無料', description: 'テロップやBGMの追加がドラッグ操作でできる' },
      { step: 4, action: 'サムネイルを作る', tool: 'Canva', cost: '無料', description: 'テンプレートを選ぶだけ' },
    ],
    freeAlternatives: [
      { original: 'HeyGen', alternative: 'D-ID', note: '無料枠あり・5分/月' },
    ],
    tags: ['AIアバター', 'HeyGen', '動画', '喋る動画', 'プレゼン'],
    relatedToolSlugs: ['chatgpt', 'heygen', 'capcut', 'canva'],
  },
  {
    id: 'wf-5',
    title: '動画に自動で字幕・テロップを入れたい',
    slug: 'auto-subtitle-video',
    shortTitle: '自動字幕・テロップ',
    description: 'Descriptに動画をアップロードするだけで音声が自動文字起こしされ、テキスト編集=動画編集という革命的な体験。10分で字幕付き動画が完成します。',
    timeEstimate: '1本あたり約10分',
    monthlyCost: '$24/月',
    monthlyCostJPY: '約3,600円',
    category: '動画',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '動画をアップロードする', tool: 'Descript', cost: '$24/月', description: '動画を入れると音声が全部テキストになる' },
      { step: 2, action: 'テキストを編集する=動画が編集される', tool: 'Descript', cost: '（同上）', description: '文章を消すと動画もカットされる。革命的に簡単' },
      { step: 3, action: '字幕スタイルを選ぶ', tool: 'Descript', cost: '（同上）', description: 'おしゃれな字幕テンプレートが用意されてる' },
    ],
    freeAlternatives: [
      { original: 'Descript', alternative: 'CapCut', note: '自動字幕機能が無料で使える' },
    ],
    tags: ['字幕', 'テロップ', '動画編集', '自動字幕', 'Descript'],
    relatedToolSlugs: ['descript', 'capcut'],
  },
  {
    id: 'wf-6',
    title: 'Instagramの投稿を自動で作りたい',
    slug: 'instagram-auto-post',
    shortTitle: 'Instagram自動投稿',
    description: 'ChatGPTで1週間分の投稿案を生成し、Canva AIで画像を作り、Bufferで予約投稿。30分で1週間分のInstagram投稿が完成します。',
    timeEstimate: '1週間分を約30分で作成',
    monthlyCost: '無料〜$13/月',
    monthlyCostJPY: '無料〜約2,000円',
    category: 'SNS運用',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '投稿テーマ・文章を作る', tool: 'ChatGPT', cost: '無料', description: '「1週間分の投稿案を作って」で7本出てくる' },
      { step: 2, action: '画像を作る', tool: 'Canva AI', cost: '無料〜', description: '「こんな画像を作って」と指示すればデザインが生成される' },
      { step: 3, action: 'ハッシュタグを生成する', tool: 'ChatGPT', cost: '無料', description: 'ジャンルを伝えるだけで最適なタグが出てくる' },
      { step: 4, action: '予約投稿する', tool: 'Buffer / Meta Business Suite', cost: '無料', description: '日時を設定しておけば自動で投稿される' },
    ],
    freeAlternatives: [
      { original: 'Canva Pro', alternative: 'Canva無料版', note: '全ステップ無料で完結可能' },
    ],
    tags: ['Instagram', 'SNS', '自動投稿', 'Canva', '画像生成'],
    relatedToolSlugs: ['chatgpt', 'canva', 'buffer'],
  },
  {
    id: 'wf-7',
    title: 'SEOに強いブログ記事を自動で書きたい',
    slug: 'seo-blog-auto-write',
    shortTitle: 'SEOブログ自動執筆',
    description: 'ラッコキーワードで需要を調べ、ChatGPTで構成、Claudeで本文執筆、Canvaでアイキャッチ。30分でSEOに強いブログ記事が完成します。',
    timeEstimate: '1記事あたり約30分',
    monthlyCost: '無料〜$20/月',
    monthlyCostJPY: '無料〜約3,000円',
    category: 'ブログ・ライティング',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: 'キーワードを調べる', tool: 'ラッコキーワード', cost: '無料', description: '検索されてる言葉が一覧で見れる' },
      { step: 2, action: '記事の構成を作る', tool: 'ChatGPT / Claude', cost: '無料', description: '「この検索キーワードで記事の見出し案を作って」でOK' },
      { step: 3, action: '記事本文を書く', tool: 'Claude', cost: '無料〜$20/月', description: '見出しごとに本文を書かせる。1記事10分で完成' },
      { step: 4, action: 'アイキャッチ画像を作る', tool: 'Canva AI', cost: '無料', description: 'ブログに貼る画像をテンプレートから作成' },
      { step: 5, action: '投稿する', tool: 'WordPress / note.com', cost: '無料', description: 'コピペして公開するだけ' },
    ],
    freeAlternatives: [
      { original: 'Claude Pro', alternative: 'Claude無料版 / ChatGPT', note: '全ステップ無料で完結可能' },
    ],
    tags: ['SEO', 'ブログ', 'ライティング', '記事作成', '自動化'],
    relatedToolSlugs: ['chatgpt', 'claude', 'canva'],
  },
  {
    id: 'wf-8',
    title: 'AIでイラストや画像を生成して販売したい',
    slug: 'ai-image-generate-sell',
    shortTitle: 'AI画像生成・販売',
    description: 'Adobe Stockで売れ筋を調べ、Midjourneyで画像生成、Canvaで補正して販売プラットフォームに出品。1枚5分、月1,500円で画像販売ビジネスを始められます。',
    timeEstimate: '1枚あたり約5分（量産可能）',
    monthlyCost: '$10/月',
    monthlyCostJPY: '約1,500円',
    category: '画像・デザイン',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '売れるジャンルを調べる', tool: 'Adobe Stock / PIXTA', cost: '無料（閲覧）', description: 'どんな画像が売れてるか検索して傾向を掴む' },
      { step: 2, action: '画像を生成する', tool: 'Midjourney', cost: '$10/月', description: '「夕日のビーチ写真風」と書くだけで画像ができる' },
      { step: 3, action: '画像を補正する', tool: 'Canva / Photopea', cost: '無料', description: 'サイズ調整やテキスト追加' },
      { step: 4, action: '販売プラットフォームに出品する', tool: 'Adobe Stock / PIXTA / BOOTH', cost: '無料', description: 'アップロードして審査通れば販売開始' },
    ],
    freeAlternatives: [
      { original: 'Midjourney', alternative: 'Microsoft Copilot', note: 'DALL-E 3ベース・無料枠あり' },
    ],
    tags: ['画像生成', 'AI画像', '販売', 'ストックフォト', 'Midjourney'],
    relatedToolSlugs: ['midjourney', 'canva'],
  },
  {
    id: 'wf-9',
    title: '自分の声を使わずにナレーションを作りたい',
    slug: 'ai-narration-no-voice',
    shortTitle: 'AIナレーション作成',
    description: 'ChatGPTで原稿を作り、ElevenLabsでAI音声に変換するだけ。5分でプロ品質のナレーションが完成。月750円から始められます。',
    timeEstimate: '1本あたり約5分',
    monthlyCost: '$5/月',
    monthlyCostJPY: '約750円',
    category: '音声・音楽',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '話す内容をテキストで書く', tool: 'ChatGPT / 自分で書く', cost: '無料', description: '原稿を用意するだけ' },
      { step: 2, action: 'AI音声に変換する', tool: 'ElevenLabs', cost: '$5/月〜', description: '男性・女性・言語を選んでテキストを貼るだけ' },
      { step: 3, action: '音声ファイルをダウンロードする', tool: 'ElevenLabs', cost: '（同上）', description: 'mp3でダウンロードして動画に合わせる' },
    ],
    freeAlternatives: [
      { original: 'ElevenLabs', alternative: 'VOICEVOX', note: '日本語特化・完全無料・商用利用可' },
    ],
    tags: ['ナレーション', 'AI音声', 'ElevenLabs', '声なし', '音声合成'],
    relatedToolSlugs: ['chatgpt', 'elevenlabs'],
  },
  {
    id: 'wf-10',
    title: '会議の議事録を自動で作りたい',
    slug: 'meeting-minutes-auto',
    shortTitle: '会議議事録自動作成',
    description: 'ZoomやGoogle Meetの録画をtl;dvで文字起こしし、ChatGPTで議事録形式にまとめる。会議後5分で完成、全ステップ無料です。',
    timeEstimate: '会議後5分で完成',
    monthlyCost: '無料',
    monthlyCostJPY: '無料',
    category: 'ビジネス効率化',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '会議を録音する', tool: 'Zoom / Google Meet', cost: '無料', description: 'いつもの会議をそのまま録画するだけ' },
      { step: 2, action: '文字起こしする', tool: 'tl;dv / Notta', cost: '無料〜', description: '録画データを入れると全部テキストになる' },
      { step: 3, action: '要約・議事録にまとめる', tool: 'ChatGPT / Claude', cost: '無料', description: '「この文字起こしを議事録形式にまとめて」で完成' },
    ],
    freeAlternatives: [
      { original: '全ステップ', alternative: '全ツール無料版', note: '全ステップ無料で完結可能' },
    ],
    tags: ['議事録', '会議', '文字起こし', '自動化', 'ビジネス'],
    relatedToolSlugs: ['chatgpt', 'claude'],
  },
];

export const workflowCategories = [
  { name: '動画', count: 5, icon: 'Video' },
  { name: 'SNS運用', count: 1, icon: 'Share2' },
  { name: 'ブログ・ライティング', count: 1, icon: 'PenTool' },
  { name: '画像・デザイン', count: 1, icon: 'Palette' },
  { name: '音声・音楽', count: 1, icon: 'Music' },
  { name: 'ビジネス効率化', count: 1, icon: 'Briefcase' },
,
  // === Phase 2 Workflows ===
  {
    id: 'wf-11',
    title: 'X(Twitter)の投稿を自動化したい',
    slug: 'x-twitter-auto-post',
    shortTitle: 'X自動投稿',
    description: 'ChatGPTでポスト文を量産し、Bufferで予約投稿。毎日の投稿作業をゼロにしてフォロワーを増やす自動化ワークフロー。',
    timeEstimate: '週30分で1週間分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'SNS運用',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '投稿ネタをリストアップ', tool: 'ChatGPT', cost: '無料', description: 'ジャンルを指定して1週間分のネタを一括生成', nextHint: 'ネタリストをStep 2で投稿文に展開する' },
      { step: 2, action: '投稿文を量産', tool: 'ChatGPT', cost: '無料', description: '各ネタから140字以内のポスト文を作成', nextHint: '作った投稿文をStep 3のBufferにコピペ' },
      { step: 3, action: '予約投稿を設定', tool: 'Buffer', cost: '無料', description: '日時を指定して1週間分まとめて予約' },
    ],
    freeAlternatives: [
      { original: 'Buffer有料プラン', alternative: 'Buffer無料プラン', note: '3チャンネル・10投稿/チャンネルまで無料' },
    ],
    tags: ['Twitter', 'X', 'SNS自動化', '予約投稿', 'Buffer'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-12',
    title: 'SNSをクロスポスト（複数同時投稿）したい',
    slug: 'sns-cross-post',
    shortTitle: 'SNSクロスポスト',
    description: '1つのコンテンツをX・Instagram・TikTok・Facebookに同時投稿。Bufferで一元管理して投稿作業を1/4に削減。',
    timeEstimate: '週40分で全SNS1週間分',
    monthlyCost: '$6',
    monthlyCostJPY: '約900円',
    category: 'SNS運用',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '元コンテンツを作成', tool: 'ChatGPT', cost: '無料', description: '1つのテーマから各SNS向けの文章を生成', nextHint: '生成した文章をStep 2でCanvaの画像と合わせる' },
      { step: 2, action: '画像を作成', tool: 'Canva', cost: '無料', description: 'テンプレートで各SNSサイズの画像を作成', nextHint: '画像と文章をStep 3のBufferにまとめて登録' },
      { step: 3, action: '全SNSに予約投稿', tool: 'Buffer', cost: '$6/月', description: '各プラットフォームに合わせた日時で予約' },
    ],
    freeAlternatives: [
      { original: 'Buffer有料プラン', alternative: 'Buffer無料＋手動投稿', note: '無料枠を超えた分は各SNSから直接投稿' },
    ],
    tags: ['クロスポスト', 'SNS一括投稿', 'Instagram', 'TikTok', 'Facebook'],
    relatedToolSlugs: ['chatgpt', 'canva-ai'],
  },
  {
    id: 'wf-13',
    title: 'SNSのコメント返信を自動化したい',
    slug: 'sns-auto-reply',
    shortTitle: 'SNS自動返信',
    description: 'ChatGPTで返信テンプレートを作り、よくあるコメントへの対応を効率化。完全自動ではなく「半自動」で人間味を残す。',
    timeEstimate: '初回設定30分・以降1日5分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'SNS運用',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'よくあるコメントを分類', tool: 'ChatGPT', cost: '無料', description: '過去のコメントをパターン別に整理', nextHint: '分類結果をStep 2で返信テンプレに変換' },
      { step: 2, action: '返信テンプレートを生成', tool: 'ChatGPT', cost: '無料', description: 'パターン別に3〜5個の返信バリエーションを作成', nextHint: 'テンプレをコピーしてStep 3で実際に返信' },
      { step: 3, action: 'テンプレを使って返信', tool: 'SNS各アプリ', cost: '無料', description: 'テンプレを微調整して投稿。コピペで10秒' },
    ],
    freeAlternatives: [
      { original: 'ChatGPT Plus', alternative: 'ChatGPT無料版', note: '無料版でも十分なテンプレート生成が可能' },
    ],
    tags: ['SNS返信', 'コメント対応', '効率化', 'テンプレート'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-14',
    title: 'noteで有料記事を書いて売りたい',
    slug: 'note-paid-article',
    shortTitle: 'note有料記事',
    description: 'Perplexityでリサーチ、Claudeで執筆、Canvaでサムネイル作成。noteの有料記事で副収入を得るワークフロー。',
    timeEstimate: '1記事あたり約60分',
    monthlyCost: '$0〜$20',
    monthlyCostJPY: '無料〜約3,000円',
    category: 'ブログ・ライティング',
    difficulty: 'intermediate' as const,
    steps: [
      { step: 1, action: 'テーマ・構成をリサーチ', tool: 'Perplexity', cost: '無料', description: '売れてるnote記事を分析し、テーマと構成を決める', nextHint: 'リサーチ結果をStep 2のClaudeに渡して執筆' },
      { step: 2, action: '記事本文を執筆', tool: 'Claude', cost: '無料〜$20/月', description: '構成に沿って5,000字以上の記事を生成・編集', nextHint: '記事が書けたらStep 3でサムネイルを作成' },
      { step: 3, action: 'サムネイルを作成', tool: 'Canva', cost: '無料', description: 'noteの推奨サイズでアイキャッチ画像を作成', nextHint: 'サムネイルと記事をStep 4でnoteに投稿' },
      { step: 4, action: 'noteに投稿・価格設定', tool: 'note', cost: '無料', description: '有料設定（100〜10,000円）で公開' },
    ],
    freeAlternatives: [
      { original: 'Claude Pro', alternative: 'Claude無料版', note: '無料版でも記事作成可能。回数制限あり' },
      { original: 'Canva Pro', alternative: 'Canva無料版', note: 'テンプレートで十分' },
    ],
    tags: ['note', '有料記事', '副業', 'ライティング', 'AI執筆'],
    relatedToolSlugs: ['perplexity', 'claude', 'canva-ai'],
  },
  {
    id: 'wf-15',
    title: 'Kindle電子書籍をAIで出版したい',
    slug: 'kindle-ai-publish',
    shortTitle: 'Kindle出版',
    description: 'ChatGPTで企画・執筆、Canvaで表紙デザイン、Kindle Direct Publishingで出版。初期費用ゼロで電子書籍を販売。',
    timeEstimate: '1冊あたり約3〜5時間',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'ブログ・ライティング',
    difficulty: 'intermediate' as const,
    steps: [
      { step: 1, action: '企画・目次を作成', tool: 'ChatGPT', cost: '無料', description: 'ジャンル分析→テーマ決定→章立てを生成', nextHint: '目次をStep 2で各章の本文に展開する' },
      { step: 2, action: '本文を執筆', tool: 'ChatGPT', cost: '無料', description: '章ごとに2,000〜3,000字を生成し編集', nextHint: '原稿完成後Step 3で表紙を作成' },
      { step: 3, action: '表紙をデザイン', tool: 'Canva', cost: '無料', description: 'Kindle表紙テンプレートで作成（1600x2560px）', nextHint: '表紙と原稿をStep 4でKDPにアップロード' },
      { step: 4, action: 'KDPで出版', tool: 'Kindle Direct Publishing', cost: '無料', description: '原稿（EPUB/PDF）と表紙をアップして価格設定・出版' },
    ],
    freeAlternatives: [
      { original: 'ChatGPT Plus', alternative: 'ChatGPT無料版', note: '無料版でも十分執筆可能' },
    ],
    tags: ['Kindle', '電子書籍', '出版', 'KDP', '副業', 'AI執筆'],
    relatedToolSlugs: ['chatgpt', 'canva-ai'],
  },
  {
    id: 'wf-16',
    title: 'AIでロゴを作りたい',
    slug: 'ai-logo-design',
    shortTitle: 'AIロゴ作成',
    description: 'Midjourneyでロゴのアイデアを生成し、Canvaで仕上げ。デザイナーに頼まず数百円でプロ級のロゴを作る。',
    timeEstimate: '約30分',
    monthlyCost: '$10',
    monthlyCostJPY: '約1,500円',
    category: '画像・デザイン',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'ロゴのアイデアを生成', tool: 'Midjourney', cost: '$10/月', description: 'プロンプトでスタイル・色・テーマを指定して複数案を生成', nextHint: '気に入ったデザインをダウンロードしてStep 2へ' },
      { step: 2, action: 'ロゴを仕上げる', tool: 'Canva', cost: '無料', description: '背景除去・テキスト追加・サイズ調整で完成', nextHint: 'PNG/SVGで書き出してStep 3で各所に設定' },
      { step: 3, action: '各プラットフォームに設定', tool: '各サービス', cost: '無料', description: 'SNS・サイト・名刺などに設定' },
    ],
    freeAlternatives: [
      { original: 'Midjourney', alternative: 'Microsoft Copilot (DALL-E 3)', note: '無料でAI画像生成が可能' },
    ],
    tags: ['ロゴ', 'デザイン', 'Midjourney', 'ブランディング'],
    relatedToolSlugs: ['midjourney', 'canva-ai'],
  },
  {
    id: 'wf-17',
    title: 'AIでプレゼン資料を自動作成したい',
    slug: 'ai-presentation',
    shortTitle: 'AIプレゼン',
    description: 'ChatGPTで構成を作り、Gammaでスライドを自動生成。テーマを入力するだけでプロ級のプレゼン資料が完成。',
    timeEstimate: '約20分',
    monthlyCost: '$0〜$10',
    monthlyCostJPY: '無料〜約1,500円',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'プレゼンの構成を作成', tool: 'ChatGPT', cost: '無料', description: '目的・対象者を入力して章立て・要点を生成', nextHint: '構成テキストをStep 2のGammaに貼り付ける' },
      { step: 2, action: 'スライドを自動生成', tool: 'Gamma', cost: '無料〜$10/月', description: 'テキストからデザイン済みスライドが自動生成', nextHint: '生成されたスライドをStep 3で微調整' },
      { step: 3, action: 'デザインを微調整', tool: 'Gamma', cost: '無料〜$10/月', description: 'レイアウト・色・画像を調整して完成' },
    ],
    freeAlternatives: [
      { original: 'Gamma有料プラン', alternative: 'Gamma無料プラン', note: '月10回まで無料で生成可能' },
    ],
    tags: ['プレゼン', 'スライド', 'Gamma', 'ビジネス', '資料作成'],
    relatedToolSlugs: ['chatgpt'],
  }
,
  {
    id: 'wf-18',
    title: 'AIで商品説明文を量産したい',
    slug: 'product-description-ai',
    shortTitle: '商品説明文AI',
    description: 'ChatGPTで商品特徴を入力するだけで、ECサイト用の魅力的な商品説明文を量産。メルカリ・Amazon・BASEに対応。',
    timeEstimate: '1商品あたり約5分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '商品情報を整理', tool: 'ChatGPT', cost: '無料', description: '商品名・特徴・ターゲットを箇条書きで入力', nextHint: '整理した情報をStep 2でプラットフォーム別に変換' },
      { step: 2, action: '説明文を生成', tool: 'ChatGPT', cost: '無料', description: 'メルカリ用・Amazon用など形式を指定して生成', nextHint: '生成した文章をStep 3でコピペして出品' },
      { step: 3, action: '各ECサイトに出品', tool: '各ECサイト', cost: '無料', description: '説明文を貼り付けて画像と一緒に出品' },
    ],
    freeAlternatives: [
      { original: 'ChatGPT Plus', alternative: 'ChatGPT無料版', note: '無料版で十分' },
    ],
    tags: ['EC', '商品説明', 'メルカリ', 'Amazon', 'コピーライティング'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-19',
    title: 'AIでメルマガ・LINEの文面を作りたい',
    slug: 'newsletter-ai',
    shortTitle: 'メルマガAI',
    description: 'ChatGPTでメルマガやLINE公式の配信文を作成。ターゲットに合わせた文面を数分で量産。',
    timeEstimate: '1通あたり約10分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '配信テーマを決める', tool: 'ChatGPT', cost: '無料', description: '目的（セール告知・情報提供等）とターゲットを指定', nextHint: 'テーマをStep 2で本文に展開する' },
      { step: 2, action: '本文を生成', tool: 'ChatGPT', cost: '無料', description: '件名・本文・CTAを一括生成。A/Bテスト用に2パターン', nextHint: '生成した文面をStep 3の配信ツールにコピペ' },
      { step: 3, action: '配信ツールで送信', tool: 'メール配信サービス', cost: '無料〜', description: 'Mailchimp・LINE公式等に貼り付けて配信設定' },
    ],
    freeAlternatives: [
      { original: 'ChatGPT Plus', alternative: 'ChatGPT無料版', note: '無料版で十分な品質' },
    ],
    tags: ['メルマガ', 'LINE公式', 'メール配信', 'コピーライティング'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-20',
    title: 'AI音楽を作ってBGMとして販売したい',
    slug: 'ai-music-creation',
    shortTitle: 'AI音楽作成',
    description: 'Sunoでテキストから楽曲を生成し、AudiostockやBGMer等のストックサイトで販売。楽器が弾けなくてもBGMビジネスを始められる。',
    timeEstimate: '1曲あたり約15分',
    monthlyCost: '$10',
    monthlyCostJPY: '約1,500円',
    category: '音声・音楽',
    difficulty: 'intermediate' as const,
    steps: [
      { step: 1, action: 'ジャンル・雰囲気を指定', tool: 'Suno', cost: '$10/月', description: 'テキストプロンプトでジャンル・テンポ・楽器を指定', nextHint: '生成された楽曲をStep 2で編集・調整' },
      { step: 2, action: '楽曲を編集', tool: 'Suno', cost: '含む', description: '気に入ったパートを繋ぎ合わせて1曲に仕上げる', nextHint: '完成した楽曲をmp3/wavでダウンロードしてStep 3へ' },
      { step: 3, action: 'ストックサイトに登録', tool: 'Audiostock等', cost: '無料', description: '楽曲をアップロードして審査→販売開始' },
    ],
    freeAlternatives: [
      { original: 'Suno有料プラン', alternative: 'Suno無料プラン', note: '月10曲まで無料生成可能。商用利用は有料プラン必要' },
    ],
    tags: ['AI音楽', 'Suno', 'BGM', '副業', 'ストック音楽'],
    relatedToolSlugs: ['suno'],
  },
  {
    id: 'wf-21',
    title: 'AIでポッドキャストを作りたい',
    slug: 'ai-podcast',
    shortTitle: 'AIポッドキャスト',
    description: 'ChatGPTで台本を書き、ElevenLabsでナレーションを生成。顔出し・声出しなしでポッドキャストを配信。',
    timeEstimate: '1エピソード約30分',
    monthlyCost: '$5',
    monthlyCostJPY: '約750円',
    category: '音声・音楽',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '台本を作成', tool: 'ChatGPT', cost: '無料', description: 'テーマ・構成・トークスクリプトを生成', nextHint: '台本テキストをStep 2のElevenLabsに貼り付ける' },
      { step: 2, action: 'ナレーションを生成', tool: 'ElevenLabs', cost: '$5/月', description: '台本から自然な音声を生成。声質も選べる', nextHint: '音声ファイルをStep 3でポッドキャスト配信' },
      { step: 3, action: 'ポッドキャストを配信', tool: 'Spotify for Podcasters', cost: '無料', description: '音声をアップロードしてSpotify・Apple Podcastに配信' },
    ],
    freeAlternatives: [
      { original: 'ElevenLabs', alternative: 'VOICEVOX', note: '無料・日本語対応。やや機械的な声' },
    ],
    tags: ['ポッドキャスト', 'AI音声', 'Spotify', '配信', '声出しなし'],
    relatedToolSlugs: ['chatgpt', 'elevenlabs'],
  },
  {
    id: 'wf-22',
    title: 'AIで翻訳・多言語コンテンツを作りたい',
    slug: 'ai-translation',
    shortTitle: 'AI翻訳',
    description: 'Claude/ChatGPTで高品質な翻訳。ブログ・商品説明・字幕を多言語展開して海外市場にリーチ。',
    timeEstimate: '1記事あたり約15分',
    monthlyCost: '$0〜$20',
    monthlyCostJPY: '無料〜約3,000円',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '原文を準備', tool: 'テキストエディタ', cost: '無料', description: '翻訳したい日本語テキストを用意', nextHint: '原文をStep 2のAIに渡して翻訳' },
      { step: 2, action: 'AIで翻訳', tool: 'Claude', cost: '無料〜$20/月', description: '「自然な英語に翻訳して」と指示。文脈に合った翻訳が可能', nextHint: '翻訳結果をStep 3でネイティブチェック' },
      { step: 3, action: '品質チェック・修正', tool: 'ChatGPT', cost: '無料', description: '別のAIで「この翻訳を改善して」とダブルチェック' },
    ],
    freeAlternatives: [
      { original: 'Claude Pro', alternative: 'Claude無料版', note: '無料版でも十分な翻訳品質' },
    ],
    tags: ['翻訳', '多言語', '英語', 'グローバル', 'ローカライズ'],
    relatedToolSlugs: ['claude', 'chatgpt'],
  },
  {
    id: 'wf-23',
    title: 'AIでレポート・報告書を自動作成したい',
    slug: 'ai-report',
    shortTitle: 'AIレポート作成',
    description: 'Perplexityでデータ収集、ChatGPTで構成・本文を生成。週次・月次レポートを30分で完成させる。',
    timeEstimate: '1レポート約30分',
    monthlyCost: '$0〜$20',
    monthlyCostJPY: '無料〜約3,000円',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'データ・情報を収集', tool: 'Perplexity', cost: '無料', description: '最新データや業界トレンドを出典付きで収集', nextHint: '収集した情報をStep 2で構成に落とし込む' },
      { step: 2, action: 'レポート構成を作成', tool: 'ChatGPT', cost: '無料', description: '目的に合わせた章立て・要点を生成', nextHint: '構成をStep 3で本文に展開' },
      { step: 3, action: '本文を執筆', tool: 'ChatGPT', cost: '無料', description: '各章の詳細を生成。グラフの説明文も作成', nextHint: '完成した文章をStep 4でスライド化' },
      { step: 4, action: '資料に仕上げ', tool: 'Gamma', cost: '無料〜$10/月', description: 'レポートをスライドまたはPDFで仕上げ' },
    ],
    freeAlternatives: [
      { original: 'Perplexity Pro', alternative: 'Perplexity無料版', note: '無料版でも基本的なリサーチ可能' },
      { original: 'Gamma有料', alternative: 'Google Slides', note: '無料で十分' },
    ],
    tags: ['レポート', '報告書', 'ビジネス文書', '自動化', 'データ分析'],
    relatedToolSlugs: ['perplexity', 'chatgpt'],
  },
  {
    id: 'wf-24',
    title: 'AIでLP（ランディングページ）を作りたい',
    slug: 'ai-landing-page',
    shortTitle: 'AI LP作成',
    description: 'ChatGPTでコピーを書き、AIウェブサイトビルダーでデザイン。コーディング不要でLPを作成・公開。',
    timeEstimate: '約60分',
    monthlyCost: '$0〜$16',
    monthlyCostJPY: '無料〜約2,400円',
    category: 'ビジネス効率化',
    difficulty: 'intermediate' as const,
    steps: [
      { step: 1, action: 'LPのコピーを作成', tool: 'ChatGPT', cost: '無料', description: 'ヘッドライン・ベネフィット・CTA・FAQを一括生成', nextHint: 'コピーテキストをStep 2のビルダーに入力' },
      { step: 2, action: 'ページを自動生成', tool: 'Framer', cost: '無料〜$16/月', description: 'AIにテキストを渡してレイアウト・デザインを自動生成', nextHint: '生成されたページをStep 3で微調整' },
      { step: 3, action: 'デザインを調整・公開', tool: 'Framer', cost: '含む', description: '画像・色・フォントを調整して独自ドメインで公開' },
    ],
    freeAlternatives: [
      { original: 'Framer有料', alternative: 'Framer無料プラン', note: 'framer.appサブドメインなら無料' },
    ],
    tags: ['LP', 'ランディングページ', 'Webサイト', 'ノーコード', 'Framer'],
    relatedToolSlugs: ['chatgpt'],
  }
,
  {
    id: 'wf-25',
    title: 'AIで動画の要約・文字起こしをしたい',
    slug: 'ai-video-summary',
    shortTitle: '動画要約AI',
    description: 'YouTube動画や会議録画をAIで文字起こし・要約。長い動画も5分で内容を把握できる。',
    timeEstimate: '1動画あたり約5分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '動画URLを取得', tool: 'YouTube等', cost: '無料', description: '要約したい動画のURLをコピー', nextHint: 'URLをStep 2のツールに貼り付ける' },
      { step: 2, action: 'AI文字起こし・要約', tool: 'Genspark', cost: '無料', description: 'URLを入力すると文字起こし＋要約を自動生成', nextHint: '要約テキストをStep 3で活用' },
      { step: 3, action: 'メモ・レポートに活用', tool: 'Notion', cost: '無料', description: '要約をNotionにコピーして整理・共有' },
    ],
    freeAlternatives: [
      { original: 'Genspark Plus', alternative: 'Genspark無料版', note: '無料版でも基本的な要約可能' },
    ],
    tags: ['動画要約', '文字起こし', 'YouTube', '要約AI', '効率化'],
    relatedToolSlugs: ['genspark', 'notion'],
  },
  {
    id: 'wf-26',
    title: 'AIでSNSのプロフィールを最適化したい',
    slug: 'sns-profile-optimize',
    shortTitle: 'SNSプロフ最適化',
    description: 'ChatGPTで魅力的なSNSプロフィール・自己紹介文を作成。フォロワーが増える文面をAIが提案。',
    timeEstimate: '約15分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'SNS運用',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '現状のプロフィールを分析', tool: 'ChatGPT', cost: '無料', description: '今のプロフィール文をAIに見せて改善点を出す', nextHint: '改善案をStep 2で新しいプロフィール文に' },
      { step: 2, action: '新プロフィールを生成', tool: 'ChatGPT', cost: '無料', description: 'ターゲット・強み・実績を入れて複数案を生成', nextHint: '気に入った案をStep 3でSNSに設定' },
      { step: 3, action: 'SNSに設定', tool: '各SNSアプリ', cost: '無料', description: 'プロフィール文・ヘッダー画像を更新' },
    ],
    freeAlternatives: [
      { original: 'ChatGPT Plus', alternative: 'ChatGPT無料版', note: '無料版で十分' },
    ],
    tags: ['プロフィール', 'SNS最適化', 'バイオ', 'フォロワー増加'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-27',
    title: 'AIでYouTubeのSEO対策をしたい',
    slug: 'youtube-seo-ai',
    shortTitle: 'YouTube SEO',
    description: 'TubeBuddyでキーワード調査、ChatGPTでタイトル・説明文・タグを最適化。再生回数を伸ばすSEO対策。',
    timeEstimate: '1動画あたり約15分',
    monthlyCost: '$0〜$5',
    monthlyCostJPY: '無料〜約750円',
    category: '動画',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'キーワードを調査', tool: 'TubeBuddy', cost: '無料〜$5/月', description: '検索ボリューム・競合度を確認してキーワード決定', nextHint: '見つけたキーワードをStep 2で活用' },
      { step: 2, action: 'タイトル・説明文を生成', tool: 'ChatGPT', cost: '無料', description: 'キーワードを含む魅力的なタイトルと説明文を複数案生成', nextHint: '生成した文面をStep 3でYouTubeに設定' },
      { step: 3, action: 'タグ・チャプターを設定', tool: 'ChatGPT', cost: '無料', description: '関連タグとタイムスタンプチャプターを生成してYouTubeに設定' },
    ],
    freeAlternatives: [
      { original: 'TubeBuddy有料', alternative: 'TubeBuddy無料版', note: '基本的なキーワード調査は無料で可能' },
    ],
    tags: ['YouTube', 'SEO', 'キーワード', '再生回数', 'TubeBuddy'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-28',
    title: 'AIでInstagramリール動画を量産したい',
    slug: 'instagram-reels-ai',
    shortTitle: 'リール量産',
    description: 'ChatGPTで台本、CapCutで編集。トレンドに乗ったInstagramリール動画を毎日投稿して集客。',
    timeEstimate: '1本あたり約20分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: '動画',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'トレンドを調査して台本作成', tool: 'ChatGPT', cost: '無料', description: 'Instagramのトレンドを指定して台本を生成', nextHint: '台本をStep 2のCapCutで動画に変換' },
      { step: 2, action: 'リール動画を編集', tool: 'CapCut', cost: '無料', description: 'テンプレートに素材と台本テキストを入れて編集', nextHint: '完成した動画をStep 3でInstagramに投稿' },
      { step: 3, action: 'Instagramに投稿', tool: 'Instagram', cost: '無料', description: 'ハッシュタグとキャプションを付けて投稿' },
    ],
    freeAlternatives: [
      { original: 'CapCut Pro', alternative: 'CapCut無料版', note: '無料版で十分な編集機能' },
    ],
    tags: ['Instagram', 'リール', '動画編集', 'CapCut', '集客'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-29',
    title: 'AIでマインドマップを自動作成したい',
    slug: 'ai-mindmap',
    shortTitle: 'AIマインドマップ',
    description: 'ChatGPTでアイデアを整理し、マインドマップツールで可視化。企画・ブレストが一瞬で整理される。',
    timeEstimate: '約10分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'テーマのアイデアを出す', tool: 'ChatGPT', cost: '無料', description: 'テーマを入力して関連アイデアをマークダウン形式で生成', nextHint: 'マークダウンテキストをStep 2のツールに貼り付け' },
      { step: 2, action: 'マインドマップに変換', tool: 'Markmap', cost: '無料', description: 'マークダウンを貼るだけでマインドマップが自動生成', nextHint: '完成したマップをStep 3で共有' },
      { step: 3, action: '画像で書き出し・共有', tool: 'Markmap', cost: '無料', description: 'PNG/SVGで書き出してチームに共有' },
    ],
    freeAlternatives: [
      { original: '有料マインドマップツール', alternative: 'Markmap（完全無料）', note: 'ブラウザ上で動くオープンソースツール' },
    ],
    tags: ['マインドマップ', 'ブレスト', 'アイデア整理', '企画'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-30',
    title: 'AIで請求書・見積書を作りたい',
    slug: 'ai-invoice',
    shortTitle: 'AI請求書作成',
    description: 'ChatGPTで項目・金額を整理し、無料テンプレートで請求書を作成。フリーランスの事務作業を効率化。',
    timeEstimate: '1枚あたり約5分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '請求内容を整理', tool: 'ChatGPT', cost: '無料', description: '作業内容・単価・数量を伝えて表形式で整理してもらう', nextHint: '整理した表をStep 2のテンプレートに入力' },
      { step: 2, action: 'テンプレートに入力', tool: 'Canva', cost: '無料', description: '請求書テンプレートに金額・宛先を入力', nextHint: 'PDFで書き出してStep 3で送付' },
      { step: 3, action: 'PDF書き出し・送付', tool: 'Canva', cost: '無料', description: 'PDFでダウンロードしてメール添付で送付' },
    ],
    freeAlternatives: [
      { original: '会計ソフト', alternative: 'Canva無料テンプレート', note: '請求書テンプレートが多数無料で使える' },
    ],
    tags: ['請求書', '見積書', 'フリーランス', '事務効率化', 'テンプレート'],
    relatedToolSlugs: ['chatgpt', 'canva-ai'],
  }
];

export function getAllWorkflows(): Workflow[] {
  return workflows;
}

export function getWorkflowBySlug(slug: string): Workflow | undefined {
  return workflows.find((wf) => wf.slug === slug);
}

export function getWorkflowsByCategory(category: string): Workflow[] {
  return workflows.filter((wf) => wf.category === category);
}

