import { Workflow } from '@/types';

export const workflows: Workflow[] = [
  {
    id: 'wf-1',
    title: 'YouTubeの動画を自動で作りたい',
    slug: 'youtube-video-auto-create',
    shortTitle: 'YouTube動画自動作成',
    description: 'ChatGPTで台本を作り、ElevenLabsでナレーション、InVideo AIで映像を自動生成。1本45分、月4,500円でYouTube動画が完成します。',
    longDescription: 'YouTubeの動画制作は、企画・台本作成・ナレーション収録・映像編集・サムネイル作成・アップロードと、多くの工程を経る必要があります。従来はこれらを一人でこなすと1本あたり8〜12時間かかることも珍しくありませんでした。しかし2025年現在、AIツールを組み合わせることでこの作業を大幅に短縮できます。このワークフローでは、ChatGPTで視聴者の関心を引く台本を自動生成し、ElevenLabsでプロ品質のナレーション音声を作成、InVideo AIで台本に合った映像・字幕・BGMを自動で組み合わせ、Canva AIでクリック率の高いサムネイルを仕上げます。最終的にYouTube Studioでアップロードと最適化を行うだけです。全工程で約45分、月額コストも4,500円程度に抑えられるため、副業や個人チャンネルの運営に最適です。動画編集の経験がなくても、各ツールがAIで自動処理してくれるため、テキスト入力と簡単な確認作業だけで完結します。まずは1本試してみて、自分のペースでチャンネルを育てていきましょう。',
    timeEstimate: '1本あたり約45分（慣れれば30分）',
    monthlyCost: '$30/月',
    monthlyCostJPY: '約4,500円',
    category: '動画',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '企画・台本を作る', tool: 'ChatGPT', cost: '無料', description: 'テーマを入力するだけで台本が出てくる', nextHint: 'この台本テキストをStep 2のElevenLabsに貼り付ける' },
      { step: 2, action: 'ナレーション音声を作る', tool: 'ElevenLabs', cost: '$5/月〜', description: 'テキストを貼るだけで人間そっくりの声になる', nextHint: '生成した音声mp3をStep 3のInVideoに読み込ませる' },
      { step: 3, action: '映像を自動生成する', tool: 'InVideo AI', cost: '$25/月', description: '台本を入れると映像・字幕・BGM全部入りの動画ができる', nextHint: '書き出した動画をダウンロードしてStep 4へ' },
      { step: 4, action: 'サムネイルを作る', tool: 'Canva', cost: '無料', description: 'テンプレを選んで文字を変えるだけ', nextHint: 'サムネイル画像を保存してStep 5で一緒にアップロード' },
      { step: 5, action: '投稿する', tool: 'YouTube Studio', cost: '無料', description: 'タイトル・説明文もStep1のChatGPTで作れる' },
    ],
    freeAlternatives: [
      { original: 'ElevenLabs', alternative: 'VOICEVOX', note: '日本語対応・完全無料' },
      { original: 'InVideo AI', alternative: 'CapCut', note: '無料・手動編集だが初心者でも使いやすい' },
    ],
    tags: ['YouTube', '動画作成', '自動化', 'AI動画', 'ナレーション'],
    relatedToolSlugs: ['chatgpt', 'elevenlabs', 'invideo', 'canva'],
  },
  {
    id: 'wf-2',
    title: '顔出しなしでYouTubeチャンネルを運営したい',
    slug: 'faceless-youtube-channel',
    shortTitle: '顔出しなしYouTube',
    description: 'TubeBuddyでニッチを分析し、Claudeで台本、ElevenLabsで音声、Pictoryで映像を自動生成。顔出し不要で月5,000円からYouTubeチャンネルを運営できます。',
    longDescription: '顔出しなしでYouTubeチャンネルを運営する「ファセレスチャンネル」は、プライバシーを守りながら収益化を目指せる手法として注目を集めています。解説系、ランキング系、環境音楽系など、顔を出さずに成立するジャンルは数多くあります。このワークフローでは、まずGensparkで検索ボリュームのあるテーマをリサーチし、ChatGPTで視聴維持率の高い台本構成を自動生成します。次にElevenLabsで自然なナレーション音声を作成し、Pictoryで台本と音声から自動的に映像を組み立てます。最後にvidIQでタイトル・タグ・説明文をSEO最適化して公開します。顔出しなしチャンネルの最大のメリットは、一度仕組みを作れば量産が可能な点です。1本あたり約60分で制作でき、月額コストも約3,500円と低コスト。チャンネル登録者1,000人・総再生4,000時間の収益化条件をクリアするまでの道のりを、AIの力で大幅に短縮できます。',
    timeEstimate: '1本あたり約60分',
    monthlyCost: '$33/月',
    monthlyCostJPY: '約5,000円',
    category: '動画',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: 'ニッチを決める', tool: 'TubeBuddy（無料版）', cost: '無料', description: 'どんなジャンルが伸びてるか数字で見れる' },
      { step: 2, action: '台本を作る', tool: 'Claude', cost: '無料', description: 'シリーズもので一貫性のある台本が得意' },
      { step: 3, action: 'AI音声を作る', tool: 'ElevenLabs', cost: '$5/月〜', description: '自分の声を録音しなくてOK' },
      { step: 4, action: '映像を自動生成する', tool: 'Pictory', cost: '$19/月', description: '台本+音声を入れると素材映像を自動で当ててくれる' },
      { step: 5, action: 'ショート動画も量産する', tool: 'OpusClip', cost: '$9/月', description: '長い動画から短い動画を自動で切り出してくれる' },
    ],
    freeAlternatives: [
      { original: 'Pictory', alternative: 'CapCut + Pexels', note: '無料素材を手動で当てる' },
      { original: 'OpusClip', alternative: 'CapCut', note: 'リサイズ機能で手動カット' },
    ],
    tags: ['YouTube', '顔出しなし', 'フェイスレス', '動画', '自動化'],
    relatedToolSlugs: ['claude', 'elevenlabs', 'pictory', 'opusclip'],
  },
  {
    id: 'wf-3',
    title: 'TikTok/リール用のショート動画を量産したい',
    slug: 'tiktok-reels-short-video',
    shortTitle: 'ショート動画量産',
    description: 'ChatGPTでネタ出し、AutoShorts.aiで自動生成、CapCutで字幕調整、Bufferで全SNSに一括投稿。1本15分、月2,900円でショート動画を量産できます。',
    longDescription: 'TikTok、Instagram Reels、YouTube Shortsなどのショート動画プラットフォームは、2025年も成長を続けています。15〜60秒の短い動画でも、バズれば数万〜数十万のリーチが可能です。このワークフローでは、ChatGPTでバズるフォーマット（フック→本題→CTA）に沿った台本を量産し、AutoShorts.aiで台本から縦型動画を自動生成します。CapCutでテロップの微調整やBGM追加などの最終仕上げを行い、Bufferで複数プラットフォームに同時予約投稿します。ショート動画は量が勝負です。毎日1〜3本を継続投稿することで、アルゴリズムに乗りやすくなります。このワークフローなら1本あたり約15分で制作でき、月額コストも約2,500円程度。通勤時間やスキマ時間でも台本を書いておけば、帰宅後にサクッと動画化できます。まずは30日間の連続投稿にチャレンジしてみましょう。',
    timeEstimate: '1本あたり約15分',
    monthlyCost: '$19/月',
    monthlyCostJPY: '約2,900円',
    category: '動画',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: 'ネタ・台本を作る', tool: 'ChatGPT', cost: '無料', description: '「バズるショート動画のネタ出して」でOK' },
      { step: 2, action: '動画を自動生成する', tool: 'AutoShorts.ai', cost: '$19/月', description: 'テーマを入れるだけで縦動画が完成する' },
      { step: 3, action: '字幕を調整する', tool: 'CapCut', cost: '無料', description: '自動字幕＋おしゃれなテロップが簡単に作れる' },
      { step: 4, action: '全SNSに一括投稿する', tool: 'Buffer', cost: '無料〜', description: 'TikTok・Instagram・YouTubeに同時投稿できる' },
    ],
    freeAlternatives: [
      { original: 'AutoShorts.ai', alternative: 'CapCut', note: 'テンプレート機能で手動作成' },
    ],
    tags: ['TikTok', 'Reels', 'ショート動画', 'SNS', '量産'],
    relatedToolSlugs: ['chatgpt', 'autoshorts', 'capcut', 'buffer'],
  },
  {
    id: 'wf-4',
    title: 'しゃべるAIアバターで動画を作りたい',
    slug: 'ai-avatar-video',
    shortTitle: 'AIアバター動画',
    description: 'ChatGPTで台本を作り、HeyGenでAIアバターが喋る動画を生成。CapCutで仕上げれば、20分で本格的なアバター動画が完成します。',
    longDescription: 'AIアバターを使った動画制作は、顔出しなしでありながら「人が話している」感覚を視聴者に与えられる革新的な手法です。企業のプレゼンテーション、eラーニング教材、商品紹介動画など、幅広い用途で活用されています。このワークフローでは、ChatGPTで話す内容の台本を構成付きで生成し、HeyGenでテキストを入力するだけでリアルなAIアバターが話す動画を作成します。CapCutでロゴやテロップを追加して仕上げ、Canva AIでサムネイルを作成して公開します。HeyGenのアバターは表情や口の動きが非常にリアルで、視聴者が AI生成と気づかないレベルの品質です。自分の顔写真からカスタムアバターを作ることもでき、「自分の分身」に話させることも可能。1本あたり約30分で制作でき、月額コストは約5,000円。動画マーケティングを始めたいけれど顔出しに抵抗がある方に最適なワークフローです。',
    timeEstimate: '1本あたり約20分',
    monthlyCost: '$29/月',
    monthlyCostJPY: '約4,400円',
    category: '動画',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '台本を作る', tool: 'ChatGPT', cost: '無料', description: '話す内容をテキストで準備するだけ' },
      { step: 2, action: 'アバター動画を生成する', tool: 'HeyGen', cost: '$29/月', description: 'テキストを入れるとAIの人物が喋ってくれる' },
      { step: 3, action: '字幕・編集する', tool: 'CapCut', cost: '無料', description: 'テロップやBGMの追加がドラッグ操作でできる' },
      { step: 4, action: 'サムネイルを作る', tool: 'Canva', cost: '無料', description: 'テンプレートを選ぶだけ' },
    ],
    freeAlternatives: [
      { original: 'HeyGen', alternative: 'D-ID', note: '無料枠あり・5分/月' },
    ],
    tags: ['AIアバター', 'HeyGen', '動画', '喋る動画', 'プレゼン'],
    relatedToolSlugs: ['chatgpt', 'heygen', 'capcut', 'canva'],
  },
  {
    id: 'wf-5',
    title: '動画に自動で字幕・テロップを入れたい',
    slug: 'auto-subtitle-video',
    shortTitle: '自動字幕・テロップ',
    description: 'Descriptに動画をアップロードするだけで音声が自動文字起こしされ、テキスト編集=動画編集という革命的な体験。10分で字幕付き動画が完成します。',
    longDescription: '動画に字幕をつける作業は、手作業で行うと10分の動画でも1〜2時間かかることがあります。しかしAI文字起こしツールを使えば、この作業を数分に短縮できます。このワークフローでは、Vrewに動画をドラッグ＆ドロップするだけでAIが自動的に音声を文字起こしし、字幕として配置します。生成された字幕を確認・修正し、フォント・色・位置などのスタイルをカスタマイズして、最終的に動画を書き出します。Vrewは日本語の認識精度が非常に高く、専門用語や固有名詞もかなり正確に拾ってくれます。字幕付き動画は視聴維持率が平均30%向上すると言われており、YouTube SEOにも好影響です。無料プランでも月120分まで利用可能なので、まずは試してみることをおすすめします。字幕をつけるだけで動画の価値が大きく変わります。',
    timeEstimate: '1本あたり約10分',
    monthlyCost: '$24/月',
    monthlyCostJPY: '約3,600円',
    category: '動画',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '動画をアップロードする', tool: 'Descript', cost: '$24/月', description: '動画を入れると音声が全部テキストになる' },
      { step: 2, action: 'テキストを編集する=動画が編集される', tool: 'Descript', cost: '（同上）', description: '文章を消すと動画もカットされる。革命的に簡単' },
      { step: 3, action: '字幕スタイルを選ぶ', tool: 'Descript', cost: '（同上）', description: 'おしゃれな字幕テンプレートが用意されてる' },
    ],
    freeAlternatives: [
      { original: 'Descript', alternative: 'CapCut', note: '自動字幕機能が無料で使える' },
    ],
    tags: ['字幕', 'テロップ', '動画編集', '自動字幕', 'Descript'],
    relatedToolSlugs: ['descript', 'capcut'],
  },
  {
    id: 'wf-6',
    title: 'Instagramの投稿を自動で作りたい',
    slug: 'instagram-auto-post',
    shortTitle: 'Instagram自動投稿',
    description: 'ChatGPTで1週間分の投稿案を生成し、Canva AIで画像を作り、Bufferで予約投稿。30分で1週間分のInstagram投稿が完成します。',
    longDescription: 'SNSの運用は継続が命です。しかし毎日の投稿ネタを考え、文章を書き、画像を作り、最適な時間に投稿するという作業を手動で続けるのは大変です。このワークフローでは、ChatGPTでInstagramに最適化されたキャプションを一括生成し、Canva AIで統一感のあるビジュアルを作成、Bufferで予約投稿します。ポイントは1回の作業で1週間分をまとめて作るバッチ処理の考え方です。日曜日に1〜2時間かけて7日分の投稿を作成し、Bufferで各日の最適な時間に予約設定すれば、平日は何もしなくてもInstagramが更新され続けます。エンゲージメント率はBufferの分析機能で確認し、反応の良かった投稿タイプを次週に増やすことで、徐々にフォロワーを増やせます。月額約3,000円で始められる自動化ワークフローです。',
    timeEstimate: '1週間分を約30分で作成',
    monthlyCost: '無料〜$13/月',
    monthlyCostJPY: '無料〜約2,000円',
    category: 'SNS運用',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '投稿テーマ・文章を作る', tool: 'ChatGPT', cost: '無料', description: '「1週間分の投稿案を作って」で7本出てくる' },
      { step: 2, action: '画像を作る', tool: 'Canva AI', cost: '無料〜', description: '「こんな画像を作って」と指示すればデザインが生成される' },
      { step: 3, action: 'ハッシュタグを生成する', tool: 'ChatGPT', cost: '無料', description: 'ジャンルを伝えるだけで最適なタグが出てくる' },
      { step: 4, action: '予約投稿する', tool: 'Buffer / Meta Business Suite', cost: '無料', description: '日時を設定しておけば自動で投稿される' },
    ],
    freeAlternatives: [
      { original: 'Canva Pro', alternative: 'Canva無料版', note: '全ステップ無料で完結可能' },
    ],
    tags: ['Instagram', 'SNS', '自動投稿', 'Canva', '画像生成'],
    relatedToolSlugs: ['chatgpt', 'canva', 'buffer'],
  },
  {
    id: 'wf-7',
    title: 'SEOに強いブログ記事を自動で書きたい',
    slug: 'seo-blog-auto-write',
    shortTitle: 'SEOブログ自動執筆',
    description: 'ラッコキーワードで需要を調べ、ChatGPTで構成、Claudeで本文執筆、Canvaでアイキャッチ。30分でSEOに強いブログ記事が完成します。',
    longDescription: 'ブログ記事の執筆は、リサーチ、構成作成、本文執筆、画像選定、SEO最適化と多くの工程が必要です。1記事あたり3〜5時間かかることも珍しくありません。このワークフローでは、Gensparkで最新情報をリサーチし、ChatGPTで検索意図に合った構成と本文を生成、Canva AIでアイキャッチ画像を作成し、WordPressに投稿します。AIが生成した原稿をそのまま公開するのではなく、自分の経験や意見を加えてオリジナリティを出すことが重要です。Googleのヘルプフルコンテンツアップデート以降、AI生成コンテンツはそのままだと評価されにくくなっています。しかしAIを下書きツールとして使い、人間が編集・加筆することで、品質の高い記事を効率的に量産できます。このワークフローなら1記事約40分、月額コストも約2,000円程度で始められます。',
    timeEstimate: '1記事あたり約30分',
    monthlyCost: '無料〜$20/月',
    monthlyCostJPY: '無料〜約3,000円',
    category: 'ブログ・ライティング',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: 'キーワードを調べる', tool: 'ラッコキーワード', cost: '無料', description: '検索されてる言葉が一覧で見れる' },
      { step: 2, action: '記事の構成を作る', tool: 'ChatGPT / Claude', cost: '無料', description: '「この検索キーワードで記事の見出し案を作って」でOK' },
      { step: 3, action: '記事本文を書く', tool: 'Claude', cost: '無料〜$20/月', description: '見出しごとに本文を書かせる。1記事10分で完成' },
      { step: 4, action: 'アイキャッチ画像を作る', tool: 'Canva AI', cost: '無料', description: 'ブログに貼る画像をテンプレートから作成' },
      { step: 5, action: '投稿する', tool: 'WordPress / note.com', cost: '無料', description: 'コピペして公開するだけ' },
    ],
    freeAlternatives: [
      { original: 'Claude Pro', alternative: 'Claude無料版 / ChatGPT', note: '全ステップ無料で完結可能' },
    ],
    tags: ['SEO', 'ブログ', 'ライティング', '記事作成', '自動化'],
    relatedToolSlugs: ['chatgpt', 'claude', 'canva'],
  },
  {
    id: 'wf-8',
    title: 'AIでイラストや画像を生成して販売したい',
    slug: 'ai-image-generate-sell',
    shortTitle: 'AI画像生成・販売',
    description: 'Adobe Stockで売れ筋を調べ、Midjourneyで画像生成、Canvaで補正して販売プラットフォームに出品。1枚5分、月1,500円で画像販売ビジネスを始められます。',
    longDescription: 'AI画像生成ツールの進化により、プロのデザイナーでなくても高品質な画像を作成できるようになりました。ストックフォトサイトへの投稿、NFTアート、ソーシャルメディア用素材、ブログのアイキャッチなど、AI生成画像の活用範囲は広がっています。このワークフローでは、Midjourneyで高品質なAI画像を生成し、Canva AIでテキストやロゴを追加して商用利用向けに仕上げ、ストックフォトサイトやSNSで販売・配布します。Midjourneyは有料プランであれば商用利用が可能で、生成した画像の著作権はユーザーに帰属します。ただし、実在する人物や企業ブランドに似た画像の商用利用は避ける必要があります。月額$10のMidjourneyプランで始められ、1日10〜20枚のペースで画像を量産すれば、ストックフォトの販売収益やSNSでの集客効果が見込めます。',
    timeEstimate: '1枚あたり約5分（量産可能）',
    monthlyCost: '$10/月',
    monthlyCostJPY: '約1,500円',
    category: '画像・デザイン',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '売れるジャンルを調べる', tool: 'Adobe Stock / PIXTA', cost: '無料（閲覧）', description: 'どんな画像が売れてるか検索して傾向を掴む' },
      { step: 2, action: '画像を生成する', tool: 'Midjourney', cost: '$10/月', description: '「夕日のビーチ写真風」と書くだけで画像ができる' },
      { step: 3, action: '画像を補正する', tool: 'Canva / Photopea', cost: '無料', description: 'サイズ調整やテキスト追加' },
      { step: 4, action: '販売プラットフォームに出品する', tool: 'Adobe Stock / PIXTA / BOOTH', cost: '無料', description: 'アップロードして審査通れば販売開始' },
    ],
    freeAlternatives: [
      { original: 'Midjourney', alternative: 'Microsoft Copilot', note: 'DALL-E 3ベース・無料枠あり' },
    ],
    tags: ['画像生成', 'AI画像', '販売', 'ストックフォト', 'Midjourney'],
    relatedToolSlugs: ['midjourney', 'canva'],
  },
  {
    id: 'wf-9',
    title: '自分の声を使わずにナレーションを作りたい',
    slug: 'ai-narration-no-voice',
    shortTitle: 'AIナレーション作成',
    description: 'ChatGPTで原稿を作り、ElevenLabsでAI音声に変換するだけ。5分でプロ品質のナレーションが完成。月750円から始められます。',
    longDescription: 'ナレーション音声の制作は、従来はプロのナレーターに依頼するか、自分で録音する必要がありました。外注すれば1本数千円〜数万円、自分で録音すれば防音環境やマイクの準備が必要です。AI音声合成ツールを使えば、テキストを入力するだけでプロ品質のナレーションが数分で完成します。このワークフローでは、ChatGPTで読み上げ原稿を会話調で生成し、ElevenLabsで声質・スピード・感情を選んで音声を生成、Audacityでノイズ除去や音量調整などの最終仕上げを行います。ElevenLabsは29言語以上に対応しており、日本語のナレーションも非常に自然です。ボイスクローン機能を使えば、自分の声をAIに学習させて自分の声で読み上げさせることも可能。ポッドキャスト、YouTube動画、プレゼン資料など、あらゆるシーンで活用できます。月額5ドルからのプランで始められます。',
    timeEstimate: '1本あたり約5分',
    monthlyCost: '$5/月',
    monthlyCostJPY: '約750円',
    category: '音声・音楽',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '話す内容をテキストで書く', tool: 'ChatGPT / 自分で書く', cost: '無料', description: '原稿を用意するだけ' },
      { step: 2, action: 'AI音声に変換する', tool: 'ElevenLabs', cost: '$5/月〜', description: '男性・女性・言語を選んでテキストを貼るだけ' },
      { step: 3, action: '音声ファイルをダウンロードする', tool: 'ElevenLabs', cost: '（同上）', description: 'mp3でダウンロードして動画に合わせる' },
    ],
    freeAlternatives: [
      { original: 'ElevenLabs', alternative: 'VOICEVOX', note: '日本語特化・完全無料・商用利用可' },
    ],
    tags: ['ナレーション', 'AI音声', 'ElevenLabs', '声なし', '音声合成'],
    relatedToolSlugs: ['chatgpt', 'elevenlabs'],
  },
  {
    id: 'wf-10',
    title: '会議の議事録を自動で作りたい',
    slug: 'meeting-minutes-auto',
    shortTitle: '会議議事録自動作成',
    description: 'ZoomやGoogle Meetの録画をtl;dvで文字起こしし、ChatGPTで議事録形式にまとめる。会議後5分で完成、全ステップ無料です。',
    longDescription: '会議の議事録作成は、多くのビジネスパーソンにとって時間のかかる面倒な作業です。会議中にメモを取りながら発言を追いかけるのは難しく、会議後にまとめると内容を忘れていることも。AI文字起こしツールを使えば、この作業を大幅に効率化できます。このワークフローでは、tl;dvで会議を自動録画・文字起こしし、ChatGPTで議事録フォーマットに整形、Notion AIで要点の抽出とアクションアイテムの一覧を作成します。tl;dvはZoomやGoogle Meetと連携しており、会議が始まると自動的に録画と文字起こしが開始されます。日本語の認識精度も高く、複数話者の識別も可能です。会議後はChatGPTが議事録のフォーマットに自動整形し、Notionで社内共有すれば、議事録作成の手間がほぼゼロになります。月額約2,000円で会議の生産性が劇的に向上します。',
    timeEstimate: '会議後5分で完成',
    monthlyCost: '無料',
    monthlyCostJPY: '無料',
    category: 'ビジネス効率化',
    difficulty: 'beginner',
    steps: [
      { step: 1, action: '会議を録音する', tool: 'Zoom / Google Meet', cost: '無料', description: 'いつもの会議をそのまま録画するだけ' },
      { step: 2, action: '文字起こしする', tool: 'tl;dv / Notta', cost: '無料〜', description: '録画データを入れると全部テキストになる' },
      { step: 3, action: '要約・議事録にまとめる', tool: 'ChatGPT / Claude', cost: '無料', description: '「この文字起こしを議事録形式にまとめて」で完成' },
    ],
    freeAlternatives: [
      { original: '全ステップ', alternative: '全ツール無料版', note: '全ステップ無料で完結可能' },
    ],
    tags: ['議事録', '会議', '文字起こし', '自動化', 'ビジネス'],
    relatedToolSlugs: ['chatgpt', 'claude'],
  },
];

export const workflowCategories = [
  { name: '動画', count: 5, icon: 'Video' },
  { name: 'SNS運用', count: 1, icon: 'Share2' },
  { name: 'ブログ・ライティング', count: 1, icon: 'PenTool' },
  { name: '画像・デザイン', count: 1, icon: 'Palette' },
  { name: '音声・音楽', count: 1, icon: 'Music' },
  { name: 'ビジネス効率化', count: 1, icon: 'Briefcase' },
,
  // === Phase 2 Workflows ===
  {
    id: 'wf-11',
    title: 'X(Twitter)の投稿を自動化したい',
    slug: 'x-twitter-auto-post',
    shortTitle: 'X自動投稿',
    description: 'ChatGPTでポスト文を量産し、Bufferで予約投稿。毎日の投稿作業をゼロにしてフォロワーを増やす自動化ワークフロー。',
    longDescription: 'X（旧Twitter）での効果的な発信は、個人ブランディングやビジネスの集客に直結します。しかし毎日質の高いツイートを考え続けるのは大変です。このワークフローでは、ChatGPTでターゲット層に刺さるツイート文を一括生成し、Canva AIで視覚的に目を引く画像やインフォグラフィックを作成、Bufferで最適な時間帯に予約投稿します。Xのアルゴリズムは投稿頻度と初速のエンゲージメントを重視するため、毎日2〜3回の定期投稿が効果的です。ChatGPTに自分の専門分野や意見を入力すれば、一貫したトーンのツイートが量産できます。1週間分をまとめて30分程度で作成し、Bufferで予約すれば平日は投稿作業が不要。Bufferの分析機能でインプレッションとエンゲージメントを確認し、効果的なコンテンツタイプを特定していきましょう。月額約2,500円で運用できます。',
    timeEstimate: '週30分で1週間分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'SNS運用',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '投稿ネタをリストアップ', tool: 'ChatGPT', cost: '無料', description: 'ジャンルを指定して1週間分のネタを一括生成', nextHint: 'ネタリストをStep 2で投稿文に展開する' },
      { step: 2, action: '投稿文を量産', tool: 'ChatGPT', cost: '無料', description: '各ネタから140字以内のポスト文を作成', nextHint: '作った投稿文をStep 3のBufferにコピペ' },
      { step: 3, action: '予約投稿を設定', tool: 'Buffer', cost: '無料', description: '日時を指定して1週間分まとめて予約' },
    ],
    freeAlternatives: [
      { original: 'Buffer有料プラン', alternative: 'Buffer無料プラン', note: '3チャンネル・10投稿/チャンネルまで無料' },
    ],
    tags: ['Twitter', 'X', 'SNS自動化', '予約投稿', 'Buffer'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-12',
    title: 'SNSをクロスポスト（複数同時投稿）したい',
    slug: 'sns-cross-post',
    shortTitle: 'SNSクロスポスト',
    description: '1つのコンテンツをX・Instagram・TikTok・Facebookに同時投稿。Bufferで一元管理して投稿作業を1/4に削減。',
    longDescription: '同じコンテンツを複数のSNSプラットフォームに展開するクロスプラットフォーム投稿は、リーチを最大化する効果的な戦略です。しかしX、Instagram、LinkedIn、Facebookはそれぞれ最適な文字数、画像サイズ、ハッシュタグの数が異なります。このワークフローでは、ChatGPTで1つのトピックから各プラットフォーム向けにトーンと長さを最適化した投稿文を生成し、Canva AIでプラットフォームごとの推奨サイズに合わせた画像を作成します。Bufferで全プラットフォームに一括予約投稿し、分析機能でパフォーマンスを比較します。1つのネタから4〜5種類の投稿を作るため、コンテンツ制作の効率が大幅に上がります。月額約3,500円で4プラットフォームの運用を自動化できるこのワークフローは、個人クリエイターから中小企業のマーケターまで幅広く活用できます。',
    timeEstimate: '週40分で全SNS1週間分',
    monthlyCost: '$6',
    monthlyCostJPY: '約900円',
    category: 'SNS運用',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '元コンテンツを作成', tool: 'ChatGPT', cost: '無料', description: '1つのテーマから各SNS向けの文章を生成', nextHint: '生成した文章をStep 2でCanvaの画像と合わせる' },
      { step: 2, action: '画像を作成', tool: 'Canva', cost: '無料', description: 'テンプレートで各SNSサイズの画像を作成', nextHint: '画像と文章をStep 3のBufferにまとめて登録' },
      { step: 3, action: '全SNSに予約投稿', tool: 'Buffer', cost: '$6/月', description: '各プラットフォームに合わせた日時で予約' },
    ],
    freeAlternatives: [
      { original: 'Buffer有料プラン', alternative: 'Buffer無料＋手動投稿', note: '無料枠を超えた分は各SNSから直接投稿' },
    ],
    tags: ['クロスポスト', 'SNS一括投稿', 'Instagram', 'TikTok', 'Facebook'],
    relatedToolSlugs: ['chatgpt', 'canva-ai'],
  },
  {
    id: 'wf-13',
    title: 'SNSのコメント返信を自動化したい',
    slug: 'sns-auto-reply',
    shortTitle: 'SNS自動返信',
    description: 'ChatGPTで返信テンプレートを作り、よくあるコメントへの対応を効率化。完全自動ではなく「半自動」で人間味を残す。',
    longDescription: 'SNSでフォロワーからのコメントやDMに迅速に対応することは、エンゲージメント率を高め、フォロワーとの信頼関係を構築する上で非常に重要です。しかし投稿数が増えるほど返信作業に追われ、本来のコンテンツ制作に時間が割けなくなります。このワークフローでは、ChatGPTでブランドのトーンに合った返信テンプレートを用意し、ManyChat等のツールで自動返信ルールを設定、特に重要なコメントだけ手動で対応する仕組みを作ります。自動返信と聞くと「冷たい」印象を持つかもしれませんが、ChatGPTで生成する返信文はパーソナライズされた温かみのある文体に設定できます。よくある質問への回答、お礼のメッセージ、商品問い合わせへの誘導など、パターン化できるものは自動化し、クレームや詳細な相談には手動対応するのがベストプラクティスです。月額約2,000円で運用可能です。',
    timeEstimate: '初回設定30分・以降1日5分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'SNS運用',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'よくあるコメントを分類', tool: 'ChatGPT', cost: '無料', description: '過去のコメントをパターン別に整理', nextHint: '分類結果をStep 2で返信テンプレに変換' },
      { step: 2, action: '返信テンプレートを生成', tool: 'ChatGPT', cost: '無料', description: 'パターン別に3〜5個の返信バリエーションを作成', nextHint: 'テンプレをコピーしてStep 3で実際に返信' },
      { step: 3, action: 'テンプレを使って返信', tool: 'SNS各アプリ', cost: '無料', description: 'テンプレを微調整して投稿。コピペで10秒' },
    ],
    freeAlternatives: [
      { original: 'ChatGPT Plus', alternative: 'ChatGPT無料版', note: '無料版でも十分なテンプレート生成が可能' },
    ],
    tags: ['SNS返信', 'コメント対応', '効率化', 'テンプレート'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-14',
    title: 'noteで有料記事を書いて売りたい',
    slug: 'note-paid-article',
    shortTitle: 'note有料記事',
    description: 'Perplexityでリサーチ、Claudeで執筆、Canvaでサムネイル作成。noteの有料記事で副収入を得るワークフロー。',
    longDescription: '有料記事やメルマガ、プレミアムコンテンツの制作には通常のブログ記事以上の品質が求められます。読者がお金を払う価値のある深い分析、独自の視点、実践的なノウハウが必要です。このワークフローでは、Perplexityで最新の一次情報や統計データをリサーチし、ChatGPTで専門性の高い長文記事を構成・執筆、Notion AIで推敲と校正を行い、最終的にnoteに有料記事として公開します。AIに任せきりではなく、リサーチ段階で独自のデータや体験を組み込み、執筆段階でAI生成文を大幅に編集することが有料コンテンツの品質を保つコツです。1記事あたり約90分で3,000〜5,000文字のプレミアム記事が完成します。noteの有料記事は100円〜10,000円で価格設定でき、フォロワーが増えれば安定した収益源になります。月額約2,500円のツールコストで始められます。',
    timeEstimate: '1記事あたり約60分',
    monthlyCost: '$0〜$20',
    monthlyCostJPY: '無料〜約3,000円',
    category: 'ブログ・ライティング',
    difficulty: 'intermediate' as const,
    steps: [
      { step: 1, action: 'テーマ・構成をリサーチ', tool: 'Perplexity', cost: '無料', description: '売れてるnote記事を分析し、テーマと構成を決める', nextHint: 'リサーチ結果をStep 2のClaudeに渡して執筆' },
      { step: 2, action: '記事本文を執筆', tool: 'Claude', cost: '無料〜$20/月', description: '構成に沿って5,000字以上の記事を生成・編集', nextHint: '記事が書けたらStep 3でサムネイルを作成' },
      { step: 3, action: 'サムネイルを作成', tool: 'Canva', cost: '無料', description: 'noteの推奨サイズでアイキャッチ画像を作成', nextHint: 'サムネイルと記事をStep 4でnoteに投稿' },
      { step: 4, action: 'noteに投稿・価格設定', tool: 'note', cost: '無料', description: '有料設定（100〜10,000円）で公開' },
    ],
    freeAlternatives: [
      { original: 'Claude Pro', alternative: 'Claude無料版', note: '無料版でも記事作成可能。回数制限あり' },
      { original: 'Canva Pro', alternative: 'Canva無料版', note: 'テンプレートで十分' },
    ],
    tags: ['note', '有料記事', '副業', 'ライティング', 'AI執筆'],
    relatedToolSlugs: ['perplexity', 'claude', 'canva-ai'],
  },
  {
    id: 'wf-15',
    title: 'Kindle電子書籍をAIで出版したい',
    slug: 'kindle-ai-publish',
    shortTitle: 'Kindle出版',
    description: 'ChatGPTで企画・執筆、Canvaで表紙デザイン、Kindle Direct Publishingで出版。初期費用ゼロで電子書籍を販売。',
    longDescription: 'Kindle電子書籍の出版は、個人が自分の知識やノウハウを収益化する有力な手段です。しかし1冊の本を書くには通常数ヶ月かかります。AIツールを活用すれば、この期間を大幅に短縮できます。このワークフローでは、ChatGPTで本の構成と各章の原稿を生成し、Notion AIで全体の推敲と一貫性チェックを行い、Canva AIで表紙デザインを作成、Amazon KDPで出版します。重要なのは、AIの出力をそのまま本にするのではなく、自分の専門知識や経験で大幅に加筆・修正することです。読者は独自の視点や実体験を求めて本を購入します。AIは構成と下書きのアシスタントとして使い、最終的な品質は人間が担保しましょう。1冊あたり2〜4週間で出版可能、月額コストは約2,000円。印税率は70%に設定でき、継続的な不労所得が期待できます。',
    timeEstimate: '1冊あたり約3〜5時間',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'ブログ・ライティング',
    difficulty: 'intermediate' as const,
    steps: [
      { step: 1, action: '企画・目次を作成', tool: 'ChatGPT', cost: '無料', description: 'ジャンル分析→テーマ決定→章立てを生成', nextHint: '目次をStep 2で各章の本文に展開する' },
      { step: 2, action: '本文を執筆', tool: 'ChatGPT', cost: '無料', description: '章ごとに2,000〜3,000字を生成し編集', nextHint: '原稿完成後Step 3で表紙を作成' },
      { step: 3, action: '表紙をデザイン', tool: 'Canva', cost: '無料', description: 'Kindle表紙テンプレートで作成（1600x2560px）', nextHint: '表紙と原稿をStep 4でKDPにアップロード' },
      { step: 4, action: 'KDPで出版', tool: 'Kindle Direct Publishing', cost: '無料', description: '原稿（EPUB/PDF）と表紙をアップして価格設定・出版' },
    ],
    freeAlternatives: [
      { original: 'ChatGPT Plus', alternative: 'ChatGPT無料版', note: '無料版でも十分執筆可能' },
    ],
    tags: ['Kindle', '電子書籍', '出版', 'KDP', '副業', 'AI執筆'],
    relatedToolSlugs: ['chatgpt', 'canva-ai'],
  },
  {
    id: 'wf-16',
    title: 'AIでロゴを作りたい',
    slug: 'ai-logo-design',
    shortTitle: 'AIロゴ作成',
    description: 'Midjourneyでロゴのアイデアを生成し、Canvaで仕上げ。デザイナーに頼まず数百円でプロ級のロゴを作る。',
    longDescription: 'ロゴデザインは企業やブランドの顔となる重要な要素ですが、プロのデザイナーに依頼すると数万円〜数十万円のコストがかかります。AIデザインツールを活用すれば、プロ品質に近いロゴを短時間で作成できます。このワークフローでは、ChatGPTでブランドコンセプトやキーワードを整理し、Midjourneyでロゴのアイデアを複数パターン生成、Canva AIで文字の配置や色の微調整を行い、最終的なロゴファイルを書き出します。AIが生成するロゴはあくまでベースであり、そこから自分のブランドに合わせて微調整することが大切です。フォントの選定、色の統一、使用するシーン（Webサイト、名刺、SNSアイコン）ごとのバリエーション作成まで含めても、約60分で完了します。月額コストは約2,500円程度。スタートアップや個人事業主のブランディングに最適なワークフローです。',
    timeEstimate: '約30分',
    monthlyCost: '$10',
    monthlyCostJPY: '約1,500円',
    category: '画像・デザイン',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'ロゴのアイデアを生成', tool: 'Midjourney', cost: '$10/月', description: 'プロンプトでスタイル・色・テーマを指定して複数案を生成', nextHint: '気に入ったデザインをダウンロードしてStep 2へ' },
      { step: 2, action: 'ロゴを仕上げる', tool: 'Canva', cost: '無料', description: '背景除去・テキスト追加・サイズ調整で完成', nextHint: 'PNG/SVGで書き出してStep 3で各所に設定' },
      { step: 3, action: '各プラットフォームに設定', tool: '各サービス', cost: '無料', description: 'SNS・サイト・名刺などに設定' },
    ],
    freeAlternatives: [
      { original: 'Midjourney', alternative: 'Microsoft Copilot (DALL-E 3)', note: '無料でAI画像生成が可能' },
    ],
    tags: ['ロゴ', 'デザイン', 'Midjourney', 'ブランディング'],
    relatedToolSlugs: ['midjourney', 'canva-ai'],
  },
  {
    id: 'wf-17',
    title: 'AIでプレゼン資料を自動作成したい',
    slug: 'ai-presentation',
    shortTitle: 'AIプレゼン',
    description: 'ChatGPTで構成を作り、Gammaでスライドを自動生成。テーマを入力するだけでプロ級のプレゼン資料が完成。',
    longDescription: 'プレゼン資料の作成は、構成を考え、スライドをデザインし、データを整理するという作業に多くの時間を取られます。通常30枚のスライドを作るのに半日〜1日かかることもあります。このワークフローでは、ChatGPTでプレゼンの構成とスライドごとの要点を生成し、Gamma AIでテキストから美しいスライドを自動生成、最終的にPowerPointやPDFに書き出します。Gamma AIはテキストを入力するだけで、レイアウト・配色・アイコン選定まで自動で行ってくれるため、デザインセンスに自信がなくても見栄えの良いスライドが完成します。社内会議、クライアントへの提案、セミナー発表など、あらゆるシーンで活用可能。1回のプレゼン資料作成が約30分に短縮され、月額コストも約2,000円程度です。空いた時間を内容の精査やリハーサルに充てることで、プレゼンの質そのものを向上させましょう。',
    timeEstimate: '約20分',
    monthlyCost: '$0〜$10',
    monthlyCostJPY: '無料〜約1,500円',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'プレゼンの構成を作成', tool: 'ChatGPT', cost: '無料', description: '目的・対象者を入力して章立て・要点を生成', nextHint: '構成テキストをStep 2のGammaに貼り付ける' },
      { step: 2, action: 'スライドを自動生成', tool: 'Gamma', cost: '無料〜$10/月', description: 'テキストからデザイン済みスライドが自動生成', nextHint: '生成されたスライドをStep 3で微調整' },
      { step: 3, action: 'デザインを微調整', tool: 'Gamma', cost: '無料〜$10/月', description: 'レイアウト・色・画像を調整して完成' },
    ],
    freeAlternatives: [
      { original: 'Gamma有料プラン', alternative: 'Gamma無料プラン', note: '月10回まで無料で生成可能' },
    ],
    tags: ['プレゼン', 'スライド', 'Gamma', 'ビジネス', '資料作成'],
    relatedToolSlugs: ['chatgpt'],
  }
,
  {
    id: 'wf-18',
    title: 'AIで商品説明文を量産したい',
    slug: 'product-description-ai',
    shortTitle: '商品説明文AI',
    description: 'ChatGPTで商品特徴を入力するだけで、ECサイト用の魅力的な商品説明文を量産。メルカリ・Amazon・BASEに対応。',
    longDescription: 'ECサイトの商品説明文は、購買率に直結する重要な要素です。しかし数百〜数千点の商品に対して、それぞれ魅力的な説明文を書くのは膨大な作業です。このワークフローでは、ChatGPTで商品の特徴やターゲット層を入力するだけで、SEOに最適化された商品説明文を一括生成します。Canva AIで商品画像のバナーを作成し、各ECプラットフォームに掲載します。ChatGPTに指示する際のコツは、ターゲットのペルソナ、商品の具体的なスペック、競合との差別化ポイントを明確に伝えることです。また、感情に訴える表現とスペック情報をバランスよく配置することで、読者の購買意欲を高められます。100商品分の説明文でも半日で完成する効率の良さが最大の魅力です。月額約1,500円のコストで、ECサイトのコンバージョン率向上が期待できます。',
    timeEstimate: '1商品あたり約5分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '商品情報を整理', tool: 'ChatGPT', cost: '無料', description: '商品名・特徴・ターゲットを箇条書きで入力', nextHint: '整理した情報をStep 2でプラットフォーム別に変換' },
      { step: 2, action: '説明文を生成', tool: 'ChatGPT', cost: '無料', description: 'メルカリ用・Amazon用など形式を指定して生成', nextHint: '生成した文章をStep 3でコピペして出品' },
      { step: 3, action: '各ECサイトに出品', tool: '各ECサイト', cost: '無料', description: '説明文を貼り付けて画像と一緒に出品' },
    ],
    freeAlternatives: [
      { original: 'ChatGPT Plus', alternative: 'ChatGPT無料版', note: '無料版で十分' },
    ],
    tags: ['EC', '商品説明', 'メルカリ', 'Amazon', 'コピーライティング'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-19',
    title: 'AIでメルマガ・LINEの文面を作りたい',
    slug: 'newsletter-ai',
    shortTitle: 'メルマガAI',
    description: 'ChatGPTでメルマガやLINE公式の配信文を作成。ターゲットに合わせた文面を数分で量産。',
    longDescription: 'メールマガジンは、SNSのアルゴリズムに左右されず、読者と直接つながれる強力なマーケティングチャネルです。しかし毎週の配信ネタを考え、読みやすい構成で書き、配信設定を行うという作業は地味に時間がかかります。このワークフローでは、Gensparkで業界の最新ニュースやトレンドを収集し、ChatGPTで読者に価値のあるニュースレターを構成・執筆、Mailchimpなどの配信ツールで予約配信します。ニュースレターの鍵は一貫したフォーマットと独自の視点です。AIに最新ニュースの要約をさせつつ、自分なりのコメントや分析を加えることで、読者が他では得られない価値を提供できます。週1配信のニュースレターなら、1回あたり約40分で作成可能。月額約2,000円のコストで、購読者との信頼関係を構築し、長期的なファンベースを育てましょう。',
    timeEstimate: '1通あたり約10分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '配信テーマを決める', tool: 'ChatGPT', cost: '無料', description: '目的（セール告知・情報提供等）とターゲットを指定', nextHint: 'テーマをStep 2で本文に展開する' },
      { step: 2, action: '本文を生成', tool: 'ChatGPT', cost: '無料', description: '件名・本文・CTAを一括生成。A/Bテスト用に2パターン', nextHint: '生成した文面をStep 3の配信ツールにコピペ' },
      { step: 3, action: '配信ツールで送信', tool: 'メール配信サービス', cost: '無料〜', description: 'Mailchimp・LINE公式等に貼り付けて配信設定' },
    ],
    freeAlternatives: [
      { original: 'ChatGPT Plus', alternative: 'ChatGPT無料版', note: '無料版で十分な品質' },
    ],
    tags: ['メルマガ', 'LINE公式', 'メール配信', 'コピーライティング'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-20',
    title: 'AI音楽を作ってBGMとして販売したい',
    slug: 'ai-music-creation',
    shortTitle: 'AI音楽作成',
    description: 'Sunoでテキストから楽曲を生成し、AudiostockやBGMer等のストックサイトで販売。楽器が弾けなくてもBGMビジネスを始められる。',
    longDescription: '音楽制作は従来、楽器の演奏スキルやDAWの操作知識が必要でしたが、AIツールの登場でこれが大きく変わりました。テキストで雰囲気やジャンルを指定するだけで、著作権フリーの楽曲が数分で生成できます。このワークフローでは、Sunoでテキストプロンプトから楽曲を生成し、Audacityで音量調整やトリミングなどの編集を行い、YouTube動画のBGMやポッドキャストのジングルとして活用します。Sunoは歌詞付きの楽曲も生成でき、ジャンルもポップ、ロック、ジャズ、クラシック、電子音楽まで幅広く対応しています。生成した楽曲は商用利用も可能で、YouTubeのコンテンツIDに引っかかる心配もありません。1曲あたり数分で生成でき、月額約1,500円のプランで始められます。動画クリエイターやポッドキャスターにとって、BGM調達の手間とコストを大幅に削減できるワークフローです。',
    timeEstimate: '1曲あたり約15分',
    monthlyCost: '$10',
    monthlyCostJPY: '約1,500円',
    category: '音声・音楽',
    difficulty: 'intermediate' as const,
    steps: [
      { step: 1, action: 'ジャンル・雰囲気を指定', tool: 'Suno', cost: '$10/月', description: 'テキストプロンプトでジャンル・テンポ・楽器を指定', nextHint: '生成された楽曲をStep 2で編集・調整' },
      { step: 2, action: '楽曲を編集', tool: 'Suno', cost: '含む', description: '気に入ったパートを繋ぎ合わせて1曲に仕上げる', nextHint: '完成した楽曲をmp3/wavでダウンロードしてStep 3へ' },
      { step: 3, action: 'ストックサイトに登録', tool: 'Audiostock等', cost: '無料', description: '楽曲をアップロードして審査→販売開始' },
    ],
    freeAlternatives: [
      { original: 'Suno有料プラン', alternative: 'Suno無料プラン', note: '月10曲まで無料生成可能。商用利用は有料プラン必要' },
    ],
    tags: ['AI音楽', 'Suno', 'BGM', '副業', 'ストック音楽'],
    relatedToolSlugs: ['suno'],
  },
  {
    id: 'wf-21',
    title: 'AIでポッドキャストを作りたい',
    slug: 'ai-podcast',
    shortTitle: 'AIポッドキャスト',
    description: 'ChatGPTで台本を書き、ElevenLabsでナレーションを生成。顔出し・声出しなしでポッドキャストを配信。',
    longDescription: 'ポッドキャストは音声コンテンツとして急成長しているメディアですが、企画、収録、編集、配信と工程が多く、継続的な運営は簡単ではありません。このワークフローでは、ChatGPTで番組の構成台本を作成し、ElevenLabsでナレーション音声を生成、AudacityでジングルやBGMの追加と音声編集を行い、各ポッドキャストプラットフォームに配信します。ElevenLabsの音声は非常に自然で、リスナーがAI音声と気づかないレベルです。複数の声を使い分けることで、対談形式のポッドキャストも一人で制作可能。1エピソードあたり約45分で完成し、月額約3,000円のコストで運営できます。通勤時間やジムでのながら聴きが定着した今、ポッドキャストは新規リスナーの獲得チャンスが大きいメディアです。まずは週1回の配信から始めてみましょう。',
    timeEstimate: '1エピソード約30分',
    monthlyCost: '$5',
    monthlyCostJPY: '約750円',
    category: '音声・音楽',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '台本を作成', tool: 'ChatGPT', cost: '無料', description: 'テーマ・構成・トークスクリプトを生成', nextHint: '台本テキストをStep 2のElevenLabsに貼り付ける' },
      { step: 2, action: 'ナレーションを生成', tool: 'ElevenLabs', cost: '$5/月', description: '台本から自然な音声を生成。声質も選べる', nextHint: '音声ファイルをStep 3でポッドキャスト配信' },
      { step: 3, action: 'ポッドキャストを配信', tool: 'Spotify for Podcasters', cost: '無料', description: '音声をアップロードしてSpotify・Apple Podcastに配信' },
    ],
    freeAlternatives: [
      { original: 'ElevenLabs', alternative: 'VOICEVOX', note: '無料・日本語対応。やや機械的な声' },
    ],
    tags: ['ポッドキャスト', 'AI音声', 'Spotify', '配信', '声出しなし'],
    relatedToolSlugs: ['chatgpt', 'elevenlabs'],
  },
  {
    id: 'wf-22',
    title: 'AIで翻訳・多言語コンテンツを作りたい',
    slug: 'ai-translation',
    shortTitle: 'AI翻訳',
    description: 'Claude/ChatGPTで高品質な翻訳。ブログ・商品説明・字幕を多言語展開して海外市場にリーチ。',
    longDescription: 'グローバル展開を目指すビジネスにとって、多言語対応は必須です。しかしプロの翻訳者に依頼すると、1記事あたり数千円〜数万円のコストと数日の納期がかかります。AI翻訳ツールを活用すれば、品質を保ちながら大幅にコストと時間を削減できます。このワークフローでは、ChatGPTまたはDeepLで原文を翻訳し、ネイティブチェック用のプロンプトで不自然な表現を検出・修正、最終的に各言語版のコンテンツを公開します。AI翻訳の精度は年々向上しており、特にDeepLは日英翻訳の品質が高く評価されています。ただし専門用語や文化的なニュアンスはAIが誤訳する場合があるため、重要な文書は必ず人間がチェックしましょう。1記事の翻訳が約15分で完了し、月額コストも無料〜約2,000円程度。まずはブログ記事やSNS投稿の多言語化から始めるのがおすすめです。',
    timeEstimate: '1記事あたり約15分',
    monthlyCost: '$0〜$20',
    monthlyCostJPY: '無料〜約3,000円',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '原文を準備', tool: 'テキストエディタ', cost: '無料', description: '翻訳したい日本語テキストを用意', nextHint: '原文をStep 2のAIに渡して翻訳' },
      { step: 2, action: 'AIで翻訳', tool: 'Claude', cost: '無料〜$20/月', description: '「自然な英語に翻訳して」と指示。文脈に合った翻訳が可能', nextHint: '翻訳結果をStep 3でネイティブチェック' },
      { step: 3, action: '品質チェック・修正', tool: 'ChatGPT', cost: '無料', description: '別のAIで「この翻訳を改善して」とダブルチェック' },
    ],
    freeAlternatives: [
      { original: 'Claude Pro', alternative: 'Claude無料版', note: '無料版でも十分な翻訳品質' },
    ],
    tags: ['翻訳', '多言語', '英語', 'グローバル', 'ローカライズ'],
    relatedToolSlugs: ['claude', 'chatgpt'],
  },
  {
    id: 'wf-23',
    title: 'AIでレポート・報告書を自動作成したい',
    slug: 'ai-report',
    shortTitle: 'AIレポート作成',
    description: 'Perplexityでデータ収集、ChatGPTで構成・本文を生成。週次・月次レポートを30分で完成させる。',
    longDescription: 'ビジネスレポートや市場調査レポートの作成は、データ収集、分析、グラフ作成、文書化と多くの工程を経る必要があり、通常は丸1日以上かかる作業です。このワークフローでは、Gensparkで最新の市場データや業界ニュースを収集し、ChatGPTでデータを分析してレポート本文を構成・執筆、Canva AIでグラフやインフォグラフィックを作成して、最終的にPDFやスライド形式で出力します。AIにレポートを書かせる際のポイントは、まずデータや事実を正確に入力し、分析のフレームワーク（SWOT分析、5フォース分析など）を指定することです。AIはフレームワークに沿って論理的な分析を展開してくれるので、人間はデータの正確性チェックと考察の追加に集中できます。月額約2,500円で半日のレポート作成が約60分に短縮されます。',
    timeEstimate: '1レポート約30分',
    monthlyCost: '$0〜$20',
    monthlyCostJPY: '無料〜約3,000円',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'データ・情報を収集', tool: 'Perplexity', cost: '無料', description: '最新データや業界トレンドを出典付きで収集', nextHint: '収集した情報をStep 2で構成に落とし込む' },
      { step: 2, action: 'レポート構成を作成', tool: 'ChatGPT', cost: '無料', description: '目的に合わせた章立て・要点を生成', nextHint: '構成をStep 3で本文に展開' },
      { step: 3, action: '本文を執筆', tool: 'ChatGPT', cost: '無料', description: '各章の詳細を生成。グラフの説明文も作成', nextHint: '完成した文章をStep 4でスライド化' },
      { step: 4, action: '資料に仕上げ', tool: 'Gamma', cost: '無料〜$10/月', description: 'レポートをスライドまたはPDFで仕上げ' },
    ],
    freeAlternatives: [
      { original: 'Perplexity Pro', alternative: 'Perplexity無料版', note: '無料版でも基本的なリサーチ可能' },
      { original: 'Gamma有料', alternative: 'Google Slides', note: '無料で十分' },
    ],
    tags: ['レポート', '報告書', 'ビジネス文書', '自動化', 'データ分析'],
    relatedToolSlugs: ['perplexity', 'chatgpt'],
  },
  {
    id: 'wf-24',
    title: 'AIでLP（ランディングページ）を作りたい',
    slug: 'ai-landing-page',
    shortTitle: 'AI LP作成',
    description: 'ChatGPTでコピーを書き、AIウェブサイトビルダーでデザイン。コーディング不要でLPを作成・公開。',
    longDescription: 'ランディングページは商品やサービスの成約率を左右する重要なページですが、デザイナーとライターに依頼すると数十万円のコストがかかります。AIツールを活用すれば、プロ品質のランディングページを短時間で作成できます。このワークフローでは、ChatGPTでコピーライティング（キャッチコピー、ベネフィット、CTA文言）を生成し、Canva AIでビジュアル素材を作成、Webflowやペライチなどのノーコードツールでページを構築します。ランディングページの成約率を高めるには、ファーストビューで価値提案を明確にし、社会的証明（レビュー、実績数値）を配置し、CTAボタンを目立たせることが重要です。ChatGPTにターゲットのペルソナと商品の強みを伝えれば、これらの要素を含んだコピーを自動生成してくれます。1ページの作成が約90分、月額約2,000円で始められます。',
    timeEstimate: '約60分',
    monthlyCost: '$0〜$16',
    monthlyCostJPY: '無料〜約2,400円',
    category: 'ビジネス効率化',
    difficulty: 'intermediate' as const,
    steps: [
      { step: 1, action: 'LPのコピーを作成', tool: 'ChatGPT', cost: '無料', description: 'ヘッドライン・ベネフィット・CTA・FAQを一括生成', nextHint: 'コピーテキストをStep 2のビルダーに入力' },
      { step: 2, action: 'ページを自動生成', tool: 'Framer', cost: '無料〜$16/月', description: 'AIにテキストを渡してレイアウト・デザインを自動生成', nextHint: '生成されたページをStep 3で微調整' },
      { step: 3, action: 'デザインを調整・公開', tool: 'Framer', cost: '含む', description: '画像・色・フォントを調整して独自ドメインで公開' },
    ],
    freeAlternatives: [
      { original: 'Framer有料', alternative: 'Framer無料プラン', note: 'framer.appサブドメインなら無料' },
    ],
    tags: ['LP', 'ランディングページ', 'Webサイト', 'ノーコード', 'Framer'],
    relatedToolSlugs: ['chatgpt'],
  }
,
  {
    id: 'wf-25',
    title: 'AIで動画の要約・文字起こしをしたい',
    slug: 'ai-video-summary',
    shortTitle: '動画要約AI',
    description: 'YouTube動画や会議録画をAIで文字起こし・要約。長い動画も5分で内容を把握できる。',
    longDescription: '長時間の動画やウェビナーの内容を短時間で把握したいというニーズは、ビジネスパーソンや学生の間で増えています。1時間の動画を視聴する代わりに、5分で要点を把握できれば、情報収集の効率が劇的に向上します。このワークフローでは、YouTube動画のURLを入力するだけでAIが自動的に文字起こしと要約を生成します。ChatGPTにトランスクリプトを入力して章立ての要約を作成し、重要なポイントをNotionに保存して知識データベースを構築します。会議の録画、オンライン講座、競合のYouTube動画分析など、活用シーンは多岐にわたります。1本の動画要約が約10分で完了し、月額コストはほぼ無料〜約1,500円。情報過多の時代に、必要な知識だけを効率的に抽出するスキルは大きな武器になります。',
    timeEstimate: '1動画あたり約5分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '動画URLを取得', tool: 'YouTube等', cost: '無料', description: '要約したい動画のURLをコピー', nextHint: 'URLをStep 2のツールに貼り付ける' },
      { step: 2, action: 'AI文字起こし・要約', tool: 'Genspark', cost: '無料', description: 'URLを入力すると文字起こし＋要約を自動生成', nextHint: '要約テキストをStep 3で活用' },
      { step: 3, action: 'メモ・レポートに活用', tool: 'Notion', cost: '無料', description: '要約をNotionにコピーして整理・共有' },
    ],
    freeAlternatives: [
      { original: 'Genspark Plus', alternative: 'Genspark無料版', note: '無料版でも基本的な要約可能' },
    ],
    tags: ['動画要約', '文字起こし', 'YouTube', '要約AI', '効率化'],
    relatedToolSlugs: ['genspark', 'notion'],
  },
  {
    id: 'wf-26',
    title: 'AIでSNSのプロフィールを最適化したい',
    slug: 'sns-profile-optimize',
    shortTitle: 'SNSプロフ最適化',
    description: 'ChatGPTで魅力的なSNSプロフィール・自己紹介文を作成。フォロワーが増える文面をAIが提案。',
    longDescription: 'SNSのプロフィールは、フォロワー獲得の第一関門です。プロフィールを見た人がフォローするかどうかは最初の3秒で決まると言われています。このワークフローでは、ChatGPTでターゲット層に刺さるプロフィール文を生成し、Canva AIでプロフィール画像やヘッダー画像を作成、各プラットフォームの推奨仕様に合わせて最適化します。効果的なSNSプロフィールには、何をしている人か、どんな価値を提供できるか、フォローするメリットは何か、の3要素が明確に含まれている必要があります。ChatGPTに自分の専門分野と提供価値を伝えれば、プラットフォームごとに最適化されたプロフィール文を提案してくれます。定期的な見直し（月1回程度）でフォロワー増加率の改善が期待できます。',
    timeEstimate: '約15分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'SNS運用',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '現状のプロフィールを分析', tool: 'ChatGPT', cost: '無料', description: '今のプロフィール文をAIに見せて改善点を出す', nextHint: '改善案をStep 2で新しいプロフィール文に' },
      { step: 2, action: '新プロフィールを生成', tool: 'ChatGPT', cost: '無料', description: 'ターゲット・強み・実績を入れて複数案を生成', nextHint: '気に入った案をStep 3でSNSに設定' },
      { step: 3, action: 'SNSに設定', tool: '各SNSアプリ', cost: '無料', description: 'プロフィール文・ヘッダー画像を更新' },
    ],
    freeAlternatives: [
      { original: 'ChatGPT Plus', alternative: 'ChatGPT無料版', note: '無料版で十分' },
    ],
    tags: ['プロフィール', 'SNS最適化', 'バイオ', 'フォロワー増加'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-27',
    title: 'AIでYouTubeのSEO対策をしたい',
    slug: 'youtube-seo-ai',
    shortTitle: 'YouTube SEO',
    description: 'TubeBuddyでキーワード調査、ChatGPTでタイトル・説明文・タグを最適化。再生回数を伸ばすSEO対策。',
    longDescription: 'YouTubeで動画を公開しても、検索やおすすめに表示されなければ再生回数は伸びません。YouTube SEOは動画の露出を最大化するために欠かせない施策です。このワークフローでは、vidIQでキーワードリサーチと競合分析を行い、ChatGPTで検索されやすいタイトル・説明文・タグを生成、Canva AIでCTRの高いサムネイルを作成します。YouTube SEOのポイントは、検索ボリュームのあるキーワードをタイトルの前半に含め、説明文の最初の2行にキーワードを自然に配置し、タグは関連キーワードを15〜20個設定することです。vidIQのスコア機能でSEO最適化度を確認しながら調整できます。1動画のSEO最適化が約20分で完了し、月額約2,000円のコストで検索流入を大幅に増やせます。',
    timeEstimate: '1動画あたり約15分',
    monthlyCost: '$0〜$5',
    monthlyCostJPY: '無料〜約750円',
    category: '動画',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'キーワードを調査', tool: 'TubeBuddy', cost: '無料〜$5/月', description: '検索ボリューム・競合度を確認してキーワード決定', nextHint: '見つけたキーワードをStep 2で活用' },
      { step: 2, action: 'タイトル・説明文を生成', tool: 'ChatGPT', cost: '無料', description: 'キーワードを含む魅力的なタイトルと説明文を複数案生成', nextHint: '生成した文面をStep 3でYouTubeに設定' },
      { step: 3, action: 'タグ・チャプターを設定', tool: 'ChatGPT', cost: '無料', description: '関連タグとタイムスタンプチャプターを生成してYouTubeに設定' },
    ],
    freeAlternatives: [
      { original: 'TubeBuddy有料', alternative: 'TubeBuddy無料版', note: '基本的なキーワード調査は無料で可能' },
    ],
    tags: ['YouTube', 'SEO', 'キーワード', '再生回数', 'TubeBuddy'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-28',
    title: 'AIでInstagramリール動画を量産したい',
    slug: 'instagram-reels-ai',
    shortTitle: 'リール量産',
    description: 'ChatGPTで台本、CapCutで編集。トレンドに乗ったInstagramリール動画を毎日投稿して集客。',
    longDescription: 'Instagram Reelsは、2025年もInstagramで最もリーチが伸びやすいコンテンツ形式です。フォロワー数に関係なく、質の高いリールは発見タブに表示され、数万人にリーチする可能性があります。このワークフローでは、ChatGPTでバズりやすいリールの台本を作成し、CapCutで縦型動画の編集とエフェクト追加を行い、Canva AIでカバー画像を作成して投稿します。リールで重要なのは最初の1〜2秒のフック（視聴者の注意を引く冒頭）です。ChatGPTにジャンルとターゲットを伝えれば、効果的なフック文を複数提案してくれます。音楽の選定はReels内のトレンドオーディオを使うとアルゴリズムの後押しを受けやすくなります。1本あたり約20分で制作でき、月額約1,500円のコストで始められます。毎日1本の投稿を目標に継続しましょう。',
    timeEstimate: '1本あたり約20分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: '動画',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'トレンドを調査して台本作成', tool: 'ChatGPT', cost: '無料', description: 'Instagramのトレンドを指定して台本を生成', nextHint: '台本をStep 2のCapCutで動画に変換' },
      { step: 2, action: 'リール動画を編集', tool: 'CapCut', cost: '無料', description: 'テンプレートに素材と台本テキストを入れて編集', nextHint: '完成した動画をStep 3でInstagramに投稿' },
      { step: 3, action: 'Instagramに投稿', tool: 'Instagram', cost: '無料', description: 'ハッシュタグとキャプションを付けて投稿' },
    ],
    freeAlternatives: [
      { original: 'CapCut Pro', alternative: 'CapCut無料版', note: '無料版で十分な編集機能' },
    ],
    tags: ['Instagram', 'リール', '動画編集', 'CapCut', '集客'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-29',
    title: 'AIでマインドマップを自動作成したい',
    slug: 'ai-mindmap',
    shortTitle: 'AIマインドマップ',
    description: 'ChatGPTでアイデアを整理し、マインドマップツールで可視化。企画・ブレストが一瞬で整理される。',
    longDescription: 'アイデア整理やプロジェクトの全体像把握にマインドマップは非常に効果的ですが、手動で作成するのは意外と時間がかかります。AIツールを活用すれば、テキスト入力だけで構造化されたマインドマップが自動生成されます。このワークフローでは、ChatGPTでトピックに関連するアイデアやサブトピックを洗い出し、Xmind AIまたはMiroでマインドマップとして視覚化、チームメンバーと共有してブレインストーミングを行います。マインドマップは会議の議題整理、ブログ記事の構成作成、新規事業のアイデア出し、学習内容の体系化など幅広い用途に使えます。ChatGPTに「このテーマについてマインドマップ形式で整理して」と指示するだけで、階層構造のテキストが出力されるので、それをマインドマップツールに貼り付けるだけです。約15分で完了し、月額コストもほぼ無料です。',
    timeEstimate: '約10分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: 'テーマのアイデアを出す', tool: 'ChatGPT', cost: '無料', description: 'テーマを入力して関連アイデアをマークダウン形式で生成', nextHint: 'マークダウンテキストをStep 2のツールに貼り付け' },
      { step: 2, action: 'マインドマップに変換', tool: 'Markmap', cost: '無料', description: 'マークダウンを貼るだけでマインドマップが自動生成', nextHint: '完成したマップをStep 3で共有' },
      { step: 3, action: '画像で書き出し・共有', tool: 'Markmap', cost: '無料', description: 'PNG/SVGで書き出してチームに共有' },
    ],
    freeAlternatives: [
      { original: '有料マインドマップツール', alternative: 'Markmap（完全無料）', note: 'ブラウザ上で動くオープンソースツール' },
    ],
    tags: ['マインドマップ', 'ブレスト', 'アイデア整理', '企画'],
    relatedToolSlugs: ['chatgpt'],
  },
  {
    id: 'wf-30',
    title: 'AIで請求書・見積書を作りたい',
    slug: 'ai-invoice',
    shortTitle: 'AI請求書作成',
    description: 'ChatGPTで項目・金額を整理し、無料テンプレートで請求書を作成。フリーランスの事務作業を効率化。',
    longDescription: 'フリーランスや個人事業主にとって、請求書の作成と管理は毎月発生する面倒な事務作業です。金額の計算ミスや送付漏れがあると信用問題にもなります。このワークフローでは、ChatGPTで請求書の項目と金額を整理し、専用テンプレートまたはInvoice AIで正式な請求書を自動生成、会計ソフトと連携して入金管理を自動化します。請求書に必要な要素（発行日、支払期限、振込先情報、源泉徴収の有無）をChatGPTに伝えれば、漏れのない請求書テンプレートを提案してくれます。毎月の定期案件は一度テンプレートを作れば、金額と日付を変更するだけで済みます。年間の収支レポートや確定申告用の書類作成も、AIが過去の請求データから自動集計してくれます。月額コストは無料〜約1,000円。事務作業を最小限にして本業に集中しましょう。',
    timeEstimate: '1枚あたり約5分',
    monthlyCost: '$0',
    monthlyCostJPY: '無料',
    category: 'ビジネス効率化',
    difficulty: 'beginner' as const,
    steps: [
      { step: 1, action: '請求内容を整理', tool: 'ChatGPT', cost: '無料', description: '作業内容・単価・数量を伝えて表形式で整理してもらう', nextHint: '整理した表をStep 2のテンプレートに入力' },
      { step: 2, action: 'テンプレートに入力', tool: 'Canva', cost: '無料', description: '請求書テンプレートに金額・宛先を入力', nextHint: 'PDFで書き出してStep 3で送付' },
      { step: 3, action: 'PDF書き出し・送付', tool: 'Canva', cost: '無料', description: 'PDFでダウンロードしてメール添付で送付' },
    ],
    freeAlternatives: [
      { original: '会計ソフト', alternative: 'Canva無料テンプレート', note: '請求書テンプレートが多数無料で使える' },
    ],
    tags: ['請求書', '見積書', 'フリーランス', '事務効率化', 'テンプレート'],
    relatedToolSlugs: ['chatgpt', 'canva-ai'],
  }
];

export function getAllWorkflows(): Workflow[] {
  return workflows;
}

export function getWorkflowBySlug(slug: string): Workflow | undefined {
  return workflows.find((wf) => wf.slug === slug);
}

export function getWorkflowsByCategory(category: string): Workflow[] {
  return workflows.filter((wf) => wf.category === category);
}

